"""Privacy-safe cloud projection for Guard action explanations."""

from __future__ import annotations

import hashlib


def build_cloud_safe_projection(
    *,
    schema_version: str,
    explanation_version: str,
    renderer_version: str,
    action_identity: str,
    locale: str,
    kind: str,
    confidence: str,
    technical_action_type: str,
    redaction_policy_version: str,
) -> dict[str, object]:
    opaque_identity = "action:sha256:" + hashlib.sha256(action_identity.encode("utf-8")).hexdigest()
    return {
        "schema_version": schema_version,
        "explanation_version": explanation_version,
        "renderer_version": renderer_version,
        "action_identity": opaque_identity,
        "canonical_identity": None,
        "catalog_digest": None,
        "locale": locale,
        "kind": kind,
        "confidence": confidence,
        "uncertainty_reasons": [],
        "everyday": {
            "headline_message_id": "guard.action.protected",
            "headline": "Protected action",
            "summary_message_id": "guard.action.cloud_safe_summary",
            "summary": "Guard recorded a protected action. Sensitive details stayed on this device.",
            "impact_message_id": None,
            "impact": None,
            "why_guard_intervened_message_id": None,
            "why_guard_intervened": None,
            "recommendation_message_id": None,
            "recommendation": None,
            "actor_label": "Guard",
            "targets": [],
            "consequences": [],
            "safer_alternatives": [],
        },
        "technical": {
            "available": False,
            "unavailable_reason": "Technical content stays on the protected device.",
            "action_type": technical_action_type,
            "command_display": None,
            "normalized_command_display": None,
            "executable": None,
            "arguments_display": None,
            "dialect": None,
            "transport": None,
            "working_scope_display": None,
            "wrappers": [],
            "segments": [],
            "extension_ids": [],
            "rule_ids": [],
            "reason_codes": [],
            "policy_source": None,
            "parse_confidence": None,
            "proof_level": None,
            "receipt_id": None,
            "action_id": None,
        },
        "redaction": {
            "level": "redacted",
            "policy_version": redaction_policy_version,
            "omitted_fields": [
                "action_identity.raw",
                "canonical_identity",
                "catalog_digest",
                "everyday.actor_label",
                "everyday.targets",
                "everyday.consequences",
                "everyday.safer_alternatives",
                "everyday.user_derived_copy",
                "technical.command",
                "technical.paths",
                "technical.arguments",
                "technical.extension_ids",
                "technical.rule_ids",
                "technical.reason_codes",
                "technical.policy_source",
                "technical.receipt_id",
                "technical.action_id",
            ],
            "truncated_fields": [],
            "secret_like_values_removed": True,
        },
    }
