"""Validated Google Cloud CLI destructive operation paths for command protection."""

from __future__ import annotations

from .command_extension_matchers import executable_path_set_matcher
from .command_path_set_matcher import ExecutablePathSetMatcher

CommandPath = tuple[str, ...]
_GCLOUD_TRACKS: tuple[CommandPath, ...] = ((), ("alpha",), ("beta",))

GCP_DESTRUCTIVE_COMMAND_PATHS: tuple[CommandPath, ...] = (
    ("projects", "delete"),
    ("resource-manager", "folders", "delete"),
    ("resource-manager", "tags", "keys", "delete"),
    ("resource-manager", "tags", "values", "delete"),
    ("iam", "service-accounts", "delete"),
    ("iam", "service-accounts", "keys", "delete"),
    ("iam", "roles", "delete"),
    ("compute", "disks", "delete"),
    ("compute", "snapshots", "delete"),
    ("compute", "images", "delete"),
    ("compute", "networks", "delete"),
    ("compute", "networks", "subnets", "delete"),
    ("compute", "firewall-rules", "delete"),
    ("compute", "routes", "delete"),
    ("compute", "addresses", "delete"),
    ("compute", "backend-services", "delete"),
    ("compute", "backend-buckets", "delete"),
    ("compute", "target-http-proxies", "delete"),
    ("compute", "target-https-proxies", "delete"),
    ("compute", "target-pools", "delete"),
    ("compute", "target-ssl-proxies", "delete"),
    ("compute", "target-tcp-proxies", "delete"),
    ("compute", "url-maps", "delete"),
    ("compute", "health-checks", "delete"),
    ("compute", "http-health-checks", "delete"),
    ("compute", "https-health-checks", "delete"),
    ("compute", "instance-templates", "delete"),
    ("compute", "instance-groups", "managed", "delete"),
    ("compute", "routers", "delete"),
    ("compute", "vpn-gateways", "delete"),
    ("compute", "vpn-tunnels", "delete"),
    ("compute", "interconnects", "delete"),
    ("compute", "ssl-certificates", "delete"),
    ("compute", "security-policies", "delete"),
    ("compute", "network-endpoint-groups", "delete"),
    ("compute", "reservations", "delete"),
    ("compute", "resource-policies", "delete"),
    ("compute", "sole-tenancy", "node-groups", "delete"),
    ("compute", "sole-tenancy", "node-templates", "delete"),
    ("compute", "interconnects", "attachments", "delete"),
    ("compute", "machine-images", "delete"),
    ("compute", "packet-mirrorings", "delete"),
    ("compute", "service-attachments", "delete"),
    ("compute", "instant-snapshots", "delete"),
    ("compute", "composite-health-checks", "delete"),
    ("container", "clusters", "delete"),
    ("container", "node-pools", "delete"),
    ("run", "services", "delete"),
    ("run", "jobs", "delete"),
    ("functions", "delete"),
    ("app", "services", "delete"),
    ("app", "versions", "delete"),
    ("artifacts", "repositories", "delete"),
    ("artifacts", "docker", "images", "delete"),
    ("artifacts", "files", "delete"),
    ("artifacts", "packages", "delete"),
    ("artifacts", "versions", "delete"),
    ("pubsub", "topics", "delete"),
    ("pubsub", "subscriptions", "delete"),
    ("pubsub", "schemas", "delete"),
    ("pubsub", "snapshots", "delete"),
    ("secrets", "delete"),
    ("secrets", "versions", "destroy"),
    ("scheduler", "jobs", "delete"),
    ("tasks", "queues", "delete"),
    ("tasks", "delete"),
    ("workflows", "delete"),
    ("deployment-manager", "deployments", "delete"),
    ("dataproc", "clusters", "delete"),
    ("bigtable", "instances", "delete"),
    ("bigtable", "clusters", "delete"),
    ("bigtable", "app-profiles", "delete"),
    ("bigtable", "backups", "delete"),
    ("bigtable", "tables", "delete"),
    ("spanner", "instances", "delete"),
    ("spanner", "databases", "delete"),
    ("spanner", "backups", "delete"),
    ("spanner", "instance-configs", "delete"),
    ("redis", "instances", "delete"),
    ("memcache", "instances", "delete"),
    ("alloydb", "clusters", "delete"),
    ("alloydb", "instances", "delete"),
    ("alloydb", "backups", "delete"),
    ("composer", "environments", "delete"),
    ("service-directory", "namespaces", "delete"),
    ("service-directory", "services", "delete"),
    ("service-directory", "endpoints", "delete"),
    ("network-services", "gateways", "delete"),
    ("network-services", "meshes", "delete"),
    ("network-services", "service-bindings", "delete"),
    ("network-services", "endpoint-policies", "delete"),
    ("network-services", "grpc-routes", "delete"),
    ("network-services", "http-routes", "delete"),
    ("network-services", "tcp-routes", "delete"),
    ("network-services", "tls-routes", "delete"),
    ("network-connectivity", "hubs", "delete"),
    ("network-connectivity", "spokes", "delete"),
    ("builds", "triggers", "delete"),
    ("builds", "worker-pools", "delete"),
    ("source", "repos", "delete"),
)


def gcp_destructive_command_matchers(
    *,
    global_options_with_values: frozenset[str],
    global_flags: frozenset[str],
) -> tuple[ExecutablePathSetMatcher, ...]:
    """Build fail-secure matchers for stable, alpha, and beta gcloud tracks."""

    return (
        executable_path_set_matcher(
            "gcloud",
            tuple((*track, *path) for track in _GCLOUD_TRACKS for path in GCP_DESTRUCTIVE_COMMAND_PATHS),
            global_options_with_values=global_options_with_values,
            global_flags=global_flags,
            fail_secure_unknown_options=True,
        ),
    )
