"""Validated AWS CLI destructive operation paths for cloud command protection."""

from __future__ import annotations

from .command_extension_matchers import executable_matcher
from .command_rules import ExecutableMatcher

CommandPath = tuple[str, ...]

AWS_DESTRUCTIVE_COMMAND_PATHS_BATCH_1: tuple[CommandPath, ...] = (
    ("acm", "delete-certificate"),
    ("acm-pca", "delete-certificate-authority"),
    ("amplify", "delete-app"),
    ("amplify", "delete-backend-environment"),
    ("amplify", "delete-branch"),
    ("amplify", "delete-domain-association"),
    ("apigateway", "delete-api-key"),
    ("apigateway", "delete-authorizer"),
    ("apigateway", "delete-base-path-mapping"),
    ("apigateway", "delete-client-certificate"),
    ("apigateway", "delete-deployment"),
    ("apigateway", "delete-documentation-part"),
    ("apigateway", "delete-documentation-version"),
    ("apigateway", "delete-domain-name"),
    ("apigateway", "delete-gateway-response"),
    ("apigateway", "delete-integration"),
    ("apigateway", "delete-integration-response"),
    ("apigateway", "delete-method"),
    ("apigateway", "delete-method-response"),
    ("apigateway", "delete-model"),
    ("apigateway", "delete-request-validator"),
    ("apigateway", "delete-resource"),
    ("apigateway", "delete-stage"),
    ("apigateway", "delete-usage-plan"),
    ("apigateway", "delete-usage-plan-key"),
    ("apigateway", "delete-vpc-link"),
    ("apigatewayv2", "delete-api-mapping"),
    ("apigatewayv2", "delete-authorizer"),
    ("apigatewayv2", "delete-deployment"),
    ("apigatewayv2", "delete-domain-name"),
    ("apigatewayv2", "delete-integration"),
    ("apigatewayv2", "delete-integration-response"),
    ("apigatewayv2", "delete-model"),
    ("apigatewayv2", "delete-route"),
    ("apigatewayv2", "delete-route-response"),
    ("apigatewayv2", "delete-stage"),
    ("apigatewayv2", "delete-vpc-link"),
    ("appconfig", "delete-application"),
    ("appconfig", "delete-configuration-profile"),
    ("appconfig", "delete-deployment-strategy"),
    ("appconfig", "delete-environment"),
    ("appsync", "delete-api-cache"),
    ("appsync", "delete-api-key"),
    ("appsync", "delete-data-source"),
    ("appsync", "delete-domain-name"),
    ("appsync", "delete-function"),
    ("appsync", "delete-graphql-api"),
    ("appsync", "delete-resolver"),
    ("appsync", "delete-type"),
    ("autoscaling", "delete-auto-scaling-group"),
    ("autoscaling", "delete-launch-configuration"),
    ("autoscaling", "delete-lifecycle-hook"),
    ("autoscaling", "delete-notification-configuration"),
    ("autoscaling", "delete-policy"),
    ("autoscaling", "delete-scheduled-action"),
    ("autoscaling", "delete-warm-pool"),
    ("backup", "delete-backup-plan"),
    ("backup", "delete-backup-selection"),
    ("backup", "delete-backup-vault"),
    ("backup", "delete-framework"),
    ("backup", "delete-recovery-point"),
    ("backup", "delete-report-plan"),
    ("backup", "delete-restore-testing-plan"),
    ("batch", "delete-compute-environment"),
    ("batch", "delete-job-queue"),
    ("batch", "delete-scheduling-policy"),
    ("cloudformation", "delete-change-set"),
    ("cloudformation", "delete-generated-template"),
    ("cloudformation", "delete-stack"),
    ("cloudformation", "delete-stack-instances"),
    ("cloudformation", "delete-stack-set"),
    ("cloudfront", "delete-cache-policy"),
    ("cloudfront", "delete-cloud-front-origin-access-identity"),
    ("cloudfront", "delete-continuous-deployment-policy"),
    ("cloudfront", "delete-field-level-encryption-config"),
    ("cloudfront", "delete-field-level-encryption-profile"),
    ("cloudfront", "delete-function"),
    ("cloudfront", "delete-key-group"),
    ("cloudfront", "delete-origin-access-control"),
    ("cloudfront", "delete-origin-request-policy"),
    ("cloudfront", "delete-public-key"),
    ("cloudfront", "delete-realtime-log-config"),
    ("cloudfront", "delete-response-headers-policy"),
    ("cloudfront", "delete-streaming-distribution"),
    ("codebuild", "delete-fleet"),
    ("codebuild", "delete-project"),
    ("codebuild", "delete-report-group"),
    ("codebuild", "delete-source-credentials"),
    ("codecommit", "delete-approval-rule-template"),
    ("codecommit", "delete-branch"),
    ("codecommit", "delete-repository"),
    ("codedeploy", "delete-application"),
    ("codedeploy", "delete-deployment-config"),
    ("codedeploy", "delete-deployment-group"),
    ("codepipeline", "delete-custom-action-type"),
    ("codepipeline", "delete-pipeline"),
    ("codepipeline", "delete-webhook"),
    ("cognito-identity", "delete-identity-pool"),
    ("cognito-idp", "delete-group"),
    ("cognito-idp", "delete-identity-provider"),
)


def aws_destructive_command_matchers(
    *,
    global_options_with_values: frozenset[str],
    global_flags: frozenset[str],
) -> tuple[ExecutableMatcher, ...]:
    """Build fail-secure matchers for the validated AWS operation matrix."""

    return tuple(
        executable_matcher(
            "aws",
            *path,
            global_options_with_values=global_options_with_values,
            global_flags=global_flags,
            fail_secure_unknown_options=True,
        )
        for path in AWS_DESTRUCTIVE_COMMAND_PATHS_BATCH_1
    )
