"""Validated Azure CLI destructive operation paths for cloud command protection."""

from __future__ import annotations

from .command_extension_matchers import executable_path_set_matcher
from .command_path_set_matcher import ExecutablePathSetMatcher

CommandPath = tuple[str, ...]

AZURE_DESTRUCTIVE_COMMAND_PATHS: tuple[CommandPath, ...] = (
    ("group", "delete"),
    ("deployment", "group", "delete"),
    ("deployment", "sub", "delete"),
    ("deployment", "tenant", "delete"),
    ("deployment", "mg", "delete"),
    ("deployment-scripts", "delete"),
    ("resource", "delete"),
    ("lock", "delete"),
    ("role", "assignment", "delete"),
    ("role", "definition", "delete"),
    ("policy", "assignment", "delete"),
    ("policy", "definition", "delete"),
    ("policy", "exemption", "delete"),
    ("identity", "delete"),
    ("ad", "app", "delete"),
    ("ad", "sp", "delete"),
    ("ad", "user", "delete"),
    ("ad", "group", "delete"),
    ("network", "vnet", "delete"),
    ("network", "vnet", "subnet", "delete"),
    ("network", "nsg", "delete"),
    ("network", "public-ip", "delete"),
    ("network", "nic", "delete"),
    ("network", "route-table", "delete"),
    ("network", "vnet-gateway", "delete"),
    ("network", "vpn-connection", "delete"),
    ("network", "application-gateway", "delete"),
    ("network", "bastion", "delete"),
    ("network", "firewall", "delete"),
    ("network", "private-endpoint", "delete"),
    ("network", "private-link-service", "delete"),
    ("network", "traffic-manager", "profile", "delete"),
    ("network", "front-door", "delete"),
    ("network", "private-dns", "zone", "delete"),
    ("network", "watcher", "connection-monitor", "delete"),
    ("network", "watcher", "flow-log", "delete"),
    ("network", "watcher", "packet-capture", "delete"),
    ("network", "cross-region-lb", "delete"),
    ("network", "nat", "gateway", "delete"),
    ("network", "local-gateway", "delete"),
    ("network", "express-route", "delete"),
    ("network", "express-route", "port", "delete"),
    ("dns-resolver", "delete"),
    ("aks", "delete"),
    ("container", "delete"),
    ("containerapp", "delete"),
    ("acr", "delete"),
    ("vmss", "delete"),
    ("disk", "delete"),
    ("disk-access", "delete"),
    ("disk-encryption-set", "delete"),
    ("snapshot", "delete"),
    ("image", "delete"),
    ("sig", "delete"),
    ("sig", "image-definition", "delete"),
    ("sig", "image-version", "delete"),
    ("capacity", "reservation", "group", "delete"),
    ("vm", "host", "group", "delete"),
    ("vm", "host", "delete"),
    ("ppg", "delete"),
    ("webapp", "delete"),
    ("functionapp", "delete"),
    ("appservice", "plan", "delete"),
    ("staticwebapp", "delete"),
    ("spring", "app", "delete"),
    ("spring", "delete"),
    ("postgres", "flexible-server", "delete"),
    ("mysql", "flexible-server", "delete"),
    ("sql", "server", "delete"),
    ("sql", "db", "delete"),
    ("sql", "mi", "delete"),
    ("cosmosdb", "delete"),
    ("redis", "delete"),
    ("managed-cassandra", "cluster", "delete"),
    ("storage", "account", "delete"),
    ("storage", "share", "delete"),
    ("storage", "queue", "delete"),
    ("storage", "table", "delete"),
    ("servicebus", "namespace", "delete"),
    ("servicebus", "queue", "delete"),
    ("servicebus", "topic", "delete"),
    ("eventhubs", "namespace", "delete"),
    ("eventhubs", "eventhub", "delete"),
    ("keyvault", "delete"),
    ("keyvault", "key", "delete"),
    ("keyvault", "secret", "delete"),
    ("keyvault", "certificate", "delete"),
    ("monitor", "log-analytics", "workspace", "delete"),
    ("monitor", "diagnostic-settings", "delete"),
    ("monitor", "action-group", "delete"),
    ("monitor", "autoscale", "delete"),
    ("apim", "api", "delete"),
    ("apim", "product", "delete"),
    ("apim", "subscription", "delete"),
    ("datafactory", "delete"),
    ("synapse", "workspace", "delete"),
    ("databricks", "workspace", "delete"),
    ("search", "service", "delete"),
    ("cognitiveservices", "account", "delete"),
    ("bot", "delete"),
)


def azure_destructive_command_matchers(
    *,
    global_options_with_values: frozenset[str],
    global_flags: frozenset[str],
) -> tuple[ExecutablePathSetMatcher, ...]:
    """Build one fail-secure matcher for the validated Azure CLI operation matrix."""

    return (
        executable_path_set_matcher(
            "az",
            AZURE_DESTRUCTIVE_COMMAND_PATHS,
            global_options_with_values=global_options_with_values,
            global_flags=global_flags,
            fail_secure_unknown_options=True,
        ),
    )
