"""Guard wrapper-mode runtime facade and shared dependency/state ownership.

Implementation modules use this namespace for live dependency lookups, so
existing runtime configuration and replacement seams keep a single owner.
"""

from __future__ import annotations

from . import runner_authority as _authority
from . import runner_constants as _constants
from . import runner_dependencies as _dependencies
from . import runner_detector_evaluation as _detector_evaluation
from . import runner_dpop as _dpop
from . import runner_errors as _errors
from . import runner_events as _events
from . import runner_execution as _execution
from . import runner_http as _http
from . import runner_identity as _identity
from . import runner_launch as _launch
from . import runner_metrics as _metrics
from . import runner_oauth_context as _oauth_context
from . import runner_oauth_refresh as _oauth_refresh
from . import runner_oauth_repair as _oauth_repair
from . import runner_payload_fields as _payload_fields
from . import runner_policy as _policy
from . import runner_prompt_intent as _prompt_intent
from . import runner_prompt_requests as _prompt_requests
from . import runner_receipt_cursor as _receipt_cursor
from . import runner_receipt_policy as _receipt_policy
from . import runner_receipt_privacy as _receipt_privacy
from . import runner_receipt_sync as _receipt_sync
from . import runner_session_payload as _session_payload
from . import runner_session_sync as _session_sync
from . import runner_supply_chain as _supply_chain

APPROVAL_REUSE_CLAIM_FAILED = _dependencies.APPROVAL_REUSE_CLAIM_FAILED
APPROVAL_REUSE_LAUNCH_IDENTITY_UNVERIFIED = _dependencies.APPROVAL_REUSE_LAUNCH_IDENTITY_UNVERIFIED
AUTHORITATIVE_DECISION_INCONSISTENT = _dependencies.AUTHORITATIVE_DECISION_INCONSISTENT
Any = _dependencies.Any
ApprovalGateError = _dependencies.ApprovalGateError
Callable = _dependencies.Callable
DetectorContext = _dependencies.DetectorContext
DetectorRegistry = _dependencies.DetectorRegistry
DetectorRunResult = _dependencies.DetectorRunResult
ExtensionControlAuthorityView = _dependencies.ExtensionControlAuthorityView
GuardAction = _dependencies.GuardAction
GuardActionEnvelope = _dependencies.GuardActionEnvelope
GuardArtifact = _dependencies.GuardArtifact
GuardConfig = _dependencies.GuardConfig
GuardDpopKeyMaterial = _dependencies.GuardDpopKeyMaterial
GuardPolicyDocument = _dependencies.GuardPolicyDocument
GuardStore = _dependencies.GuardStore
HarnessAdapter = _dependencies.HarnessAdapter
HarnessContext = _dependencies.HarnessContext
HarnessDetection = _dependencies.HarnessDetection
Iterable = _dependencies.Iterable
MANAGED_POLICY_BUNDLE_KEYRING_PROVENANCE_STATE_KEY = _dependencies.MANAGED_POLICY_BUNDLE_KEYRING_PROVENANCE_STATE_KEY
Mapping = _dependencies.Mapping
POLICY_BUNDLE_RULE_MATCHER_FAMILIES = _dependencies.POLICY_BUNDLE_RULE_MATCHER_FAMILIES
POLICY_BUNDLE_V2_CONTRACT = _dependencies.POLICY_BUNDLE_V2_CONTRACT
ParsedManagedControlsPolicy = _dependencies.ParsedManagedControlsPolicy
Path = _dependencies.Path
PolicyBundleVerificationKey = _dependencies.PolicyBundleVerificationKey
PolicyCompilationError = _dependencies.PolicyCompilationError
PolicyDecision = _dependencies.PolicyDecision
PromptRequest = _dependencies.PromptRequest
RemediationAction = _dependencies.RemediationAction
RiskSignalV2 = _dependencies.RiskSignalV2
Sequence = _dependencies.Sequence
SupplyChainBundleError = _dependencies.SupplyChainBundleError
SupplyChainVerificationKey = _dependencies.SupplyChainVerificationKey
VALID_RECEIPT_REDACTION_LEVELS = _dependencies.VALID_RECEIPT_REDACTION_LEVELS
__version__ = _dependencies.__version__
_daemon_version_supported = _dependencies._daemon_version_supported
_decode_oauth_access_token_claims = _dependencies._decode_oauth_access_token_claims
_managed_controls_lkg_capabilities = _dependencies._managed_controls_lkg_capabilities
_managed_controls_negotiated_capabilities = _dependencies._managed_controls_negotiated_capabilities
_managed_controls_runtime_sync_posture = _dependencies._managed_controls_runtime_sync_posture
_materialize_policy_bundle_decisions = _dependencies._materialize_policy_bundle_decisions
_validate_extension_catalog_sync_response = _dependencies._validate_extension_catalog_sync_response
activate_with_reason = _dependencies.activate_with_reason
apply_custom_extension_continuity_from_sync = _dependencies.apply_custom_extension_continuity_from_sync
base64 = _dependencies.base64
best_effort_access_token = _dependencies.best_effort_access_token
build_authoritative_decision = _dependencies.build_authoritative_decision
build_builtin_extension_catalog_wire = _dependencies.build_builtin_extension_catalog_wire
build_cloud_exceptions_from_policy_bundle = _dependencies.build_cloud_exceptions_from_policy_bundle
build_oauth_package_firewall_entitlement = _dependencies.build_oauth_package_firewall_entitlement
build_runtime_launch_identity = _dependencies.build_runtime_launch_identity
build_runtime_session_event = _dependencies.build_runtime_session_event
cached_policy_bundle_validation = _dependencies.cached_policy_bundle_validation
cast = _dependencies.cast
cloud_exception_to_dict = _dependencies.cloud_exception_to_dict
compile_policy_document = _dependencies.compile_policy_document
compose_action_from_signals = _dependencies.compose_action_from_signals
computed_policy_bundle_hash = _dependencies.computed_policy_bundle_hash
contextmanager = _dependencies.contextmanager
dataclass = _dependencies.dataclass
datetime = _dependencies.datetime
decode_dss_signature = _dependencies.decode_dss_signature
dedupe_cloud_exceptions = _dependencies.dedupe_cloud_exceptions
detect_prompt_injection_requests = _dependencies.detect_prompt_injection_requests
ec = _dependencies.ec
ecosystem_support_matrix = _dependencies.ecosystem_support_matrix
effective_managed_controls_for_activation = _dependencies.effective_managed_controls_for_activation
effective_policy_bundle_acknowledgement = _dependencies.effective_policy_bundle_acknowledgement
evaluation_authority_error = _dependencies.evaluation_authority_error
extract_cloud_user_profile = _dependencies.extract_cloud_user_profile
hashes = _dependencies.hashes
hashlib = _dependencies.hashlib
importlib = _dependencies.importlib
io = _dependencies.io
is_guard_action = _dependencies.is_guard_action
json = _dependencies.json
load_supply_chain_bundle_response = _dependencies.load_supply_chain_bundle_response
load_supply_chain_verification_keys = _dependencies.load_supply_chain_verification_keys
local_receipt_redaction_level = _dependencies.local_receipt_redaction_level
managed_urlopen = _dependencies.managed_urlopen
most_restrictive_guard_action = _dependencies.most_restrictive_guard_action
non_empty_string = _dependencies.non_empty_string
oauth_binding_from_credentials = _dependencies.oauth_binding_from_credentials
oauth_binding_metadata = _dependencies.oauth_binding_metadata
oauth_refresh_binding = _dependencies.oauth_refresh_binding
os = _dependencies.os
package_shim_cloud_coverage = _dependencies.package_shim_cloud_coverage
parse_approval_context_token = _dependencies.parse_approval_context_token
persist_activation_rejection = _dependencies.persist_activation_rejection
policy_bundle_acceptance_checkpoint = _dependencies.policy_bundle_acceptance_checkpoint
policy_bundle_is_enforceable = _dependencies.policy_bundle_is_enforceable
policy_bundle_is_version_downgrade = _dependencies.policy_bundle_is_version_downgrade
policy_bundle_keyring_payload = _dependencies.policy_bundle_keyring_payload
policy_bundle_rejection_message = _dependencies.policy_bundle_rejection_message
prepare_extension_catalog_handshake = _dependencies.prepare_extension_catalog_handshake
re = _dependencies.re
rebuild_artifact_authority = _dependencies.rebuild_artifact_authority
reconcile_connect_state_with_oauth_entitlement = _dependencies.reconcile_connect_state_with_oauth_entitlement
redact_sensitive_text = _dependencies.redact_sensitive_text
redacted_workspace_label = _dependencies.redacted_workspace_label
register_default_detectors = _dependencies.register_default_detectors
replace = _dependencies.replace
resolve_guard_oauth_client_config = _dependencies.resolve_guard_oauth_client_config
resolved_runtime_launch_argv = _dependencies.resolved_runtime_launch_argv
runtime_launch_identity_is_reusable = _dependencies.runtime_launch_identity_is_reusable
runtime_session_success_summary = _dependencies.runtime_session_success_summary
runtime_summary_device_id = _dependencies.runtime_summary_device_id
serialization = _dependencies.serialization
socket = _dependencies.socket
subprocess = _dependencies.subprocess
suppress = _dependencies.suppress
threading = _dependencies.threading
time = _dependencies.time
timedelta = _dependencies.timedelta
timezone = _dependencies.timezone
urllib = _dependencies.urllib
urlsafe_b64encode = _dependencies.urlsafe_b64encode
uuid4 = _dependencies.uuid4
validate_guard_sync_endpoint = _dependencies.validate_guard_sync_endpoint
validate_policy_bundle_v2_transition = _dependencies.validate_policy_bundle_v2_transition
validate_synced_policy_bundle = _dependencies.validate_synced_policy_bundle
validated_managed_controls_candidate = _dependencies.validated_managed_controls_candidate
validated_policy_bundle_v2_acknowledgement = _dependencies.validated_policy_bundle_v2_acknowledgement
validated_review_verification_keys_from_sync = _dependencies.validated_review_verification_keys_from_sync
validated_synced_policy_bundle = _dependencies.validated_synced_policy_bundle
verify_supply_chain_bundle_response = _dependencies.verify_supply_chain_bundle_response

_APPROVAL_METADATA_KEYS = _constants._APPROVAL_METADATA_KEYS
_APPROVAL_REUSE_CONTEXT_CHANGED_AFTER_CLAIM = _constants._APPROVAL_REUSE_CONTEXT_CHANGED_AFTER_CLAIM
_CLOUD_REVIEW_PRIVACY_PROJECTION_MARKER = _constants._CLOUD_REVIEW_PRIVACY_PROJECTION_MARKER
_DESTRUCTIVE_PROMPT_PATTERNS = _constants._DESTRUCTIVE_PROMPT_PATTERNS
_DOCUMENT_PROMPT_ACTION_PATTERN = _constants._DOCUMENT_PROMPT_ACTION_PATTERN
_DOCUMENT_PROMPT_CONTEXT_PATTERN = _constants._DOCUMENT_PROMPT_CONTEXT_PATTERN
_DOCUMENT_PROMPT_GUARDRAIL_PATTERN = _constants._DOCUMENT_PROMPT_GUARDRAIL_PATTERN
_DOCUMENT_PROMPT_STRONG_GUARDRAIL_PATTERN = _constants._DOCUMENT_PROMPT_STRONG_GUARDRAIL_PATTERN
_DOCUMENT_PROMPT_TARGET_PATTERN = _constants._DOCUMENT_PROMPT_TARGET_PATTERN
_EXCEPTION_EXPIRY_ALERT_WINDOW_HOURS = _constants._EXCEPTION_EXPIRY_ALERT_WINDOW_HOURS
_EXFIL_ACTIONS = _constants._EXFIL_ACTIONS
_EXFIL_ARTIFACTS = _constants._EXFIL_ARTIFACTS
_EXFIL_DESTINATIONS = _constants._EXFIL_DESTINATIONS
_EXFIL_NAMED_REMOTE_TARGETS = _constants._EXFIL_NAMED_REMOTE_TARGETS
_EXFIL_PROMPT_PATTERNS = _constants._EXFIL_PROMPT_PATTERNS
_EXFIL_REMOTE_TARGETS = _constants._EXFIL_REMOTE_TARGETS
_FOLLOWING_SECRET_REFERENCE_PATTERN = _constants._FOLLOWING_SECRET_REFERENCE_PATTERN
_GUARD_BYPASS_PROMPT_PATTERN = _constants._GUARD_BYPASS_PROMPT_PATTERN
_GUARD_DPOP_REQUEST_CONTEXT_LIMIT = _constants._GUARD_DPOP_REQUEST_CONTEXT_LIMIT
_GUARD_EVENTS_ENDPOINT_UNAVAILABLE_RETRY_MINUTES = _constants._GUARD_EVENTS_ENDPOINT_UNAVAILABLE_RETRY_MINUTES
_GUARD_RUN_LATE_CREDENTIAL_ENV_KEYS = _constants._GUARD_RUN_LATE_CREDENTIAL_ENV_KEYS
_GUARD_SYNC_USER_AGENT = _constants._GUARD_SYNC_USER_AGENT
_HERMES_GUARD_TOKEN_ENV_KEY = _constants._HERMES_GUARD_TOKEN_ENV_KEY
_INSTALL_TIME_STOP_EVENTS = _constants._INSTALL_TIME_STOP_EVENTS
_INTERACTIVE_ALLOW_OVERRIDE_LABELS = _constants._INTERACTIVE_ALLOW_OVERRIDE_LABELS
_NEGATED_SECRET_READ_PATTERN = _constants._NEGATED_SECRET_READ_PATTERN
_OAUTH_ACCESS_TOKEN_REFRESH_SKEW_SECONDS = _constants._OAUTH_ACCESS_TOKEN_REFRESH_SKEW_SECONDS
_OAUTH_INVALID_GRANT_MAX_ATTEMPTS = _constants._OAUTH_INVALID_GRANT_MAX_ATTEMPTS
_OAUTH_INVALID_GRANT_RETRY_DELAY_SECONDS = _constants._OAUTH_INVALID_GRANT_RETRY_DELAY_SECONDS
_PAIN_SIGNAL_EVENTS = _constants._PAIN_SIGNAL_EVENTS
_PAIN_SIGNAL_RETRY_TIMEOUT_SECONDS = _constants._PAIN_SIGNAL_RETRY_TIMEOUT_SECONDS
_PAIN_SIGNAL_TIMEOUT_SECONDS = _constants._PAIN_SIGNAL_TIMEOUT_SECONDS
_PLAN_403_KEYWORDS = _constants._PLAN_403_KEYWORDS
_POLICY_BUNDLE_VERSIONS = _constants._POLICY_BUNDLE_VERSIONS
_POLICY_CANONICAL_ENFORCEMENT_ENV = _constants._POLICY_CANONICAL_ENFORCEMENT_ENV
_POLICY_CONTRACTS = _constants._POLICY_CONTRACTS
_POLICY_DOCUMENT_VERSIONS = _constants._POLICY_DOCUMENT_VERSIONS
_POLICY_YAML_IMPORT_ENV = _constants._POLICY_YAML_IMPORT_ENV
_PROMPT_SENTENCE_BOUNDARY_PATTERN = _constants._PROMPT_SENTENCE_BOUNDARY_PATTERN
_RECEIPT_COMMAND_DETAIL_BACKFILL_DAYS = _constants._RECEIPT_COMMAND_DETAIL_BACKFILL_DAYS
_RECEIPT_COMMAND_DETAIL_BACKFILL_FLAG = _constants._RECEIPT_COMMAND_DETAIL_BACKFILL_FLAG
_RECEIPT_COMMAND_DETAIL_BACKFILL_LIMIT = _constants._RECEIPT_COMMAND_DETAIL_BACKFILL_LIMIT
_RECEIPT_COMMAND_DETAIL_BACKFILL_MARKER = _constants._RECEIPT_COMMAND_DETAIL_BACKFILL_MARKER
_RECEIPT_REDACTION_LEVEL_RANK = _constants._RECEIPT_REDACTION_LEVEL_RANK
_RECEIPT_SYNC_BATCH_SIZE = _constants._RECEIPT_SYNC_BATCH_SIZE
_RECEIPT_SYNC_CURSOR_BACKFILL_ROWS = _constants._RECEIPT_SYNC_CURSOR_BACKFILL_ROWS
_RECEIPT_SYNC_CURSOR_PAGE_SIZE = _constants._RECEIPT_SYNC_CURSOR_PAGE_SIZE
_RELAXED_RECEIPT_REDACTION_RESYNC_MARKER = _constants._RELAXED_RECEIPT_REDACTION_RESYNC_MARKER
_RUNTIME_DETECTOR_RESULT_KEYS = _constants._RUNTIME_DETECTOR_RESULT_KEYS
_RUNTIME_DETECTOR_REVIEW_REASON = _constants._RUNTIME_DETECTOR_REVIEW_REASON
_RUNTIME_DETECTOR_WARN_REASON = _constants._RUNTIME_DETECTOR_WARN_REASON
_RUNTIME_SYNC_RETRY_TIMEOUT_SECONDS = _constants._RUNTIME_SYNC_RETRY_TIMEOUT_SECONDS
_RUNTIME_SYNC_TIMEOUT_SECONDS = _constants._RUNTIME_SYNC_TIMEOUT_SECONDS
_SAME_SENTENCE_40 = _constants._SAME_SENTENCE_40
_SAME_SENTENCE_80 = _constants._SAME_SENTENCE_80
_SECRET_ABSOLUTE_HINTS = _constants._SECRET_ABSOLUTE_HINTS
_SECRET_READ_INTENT_PATTERN = _constants._SECRET_READ_INTENT_PATTERN
_SECRET_REQUEST_PATTERNS = _constants._SECRET_REQUEST_PATTERNS
_SUBPROCESS_PROMPT_PATTERNS = _constants._SUBPROCESS_PROMPT_PATTERNS
_SYNC_HTTP_RETRY_TIMEOUT_SECONDS = _constants._SYNC_HTTP_RETRY_TIMEOUT_SECONDS
_SYNC_HTTP_TIMEOUT_SECONDS = _constants._SYNC_HTTP_TIMEOUT_SECONDS
_SYNC_RETRYABLE_GATEWAY_MAX_ATTEMPTS = _constants._SYNC_RETRYABLE_GATEWAY_MAX_ATTEMPTS
_SYNC_RETRYABLE_GATEWAY_STATUS_CODES = _constants._SYNC_RETRYABLE_GATEWAY_STATUS_CODES

GuardSyncAuthorizationExpiredError = _errors.GuardSyncAuthorizationExpiredError
GuardSyncEndpointUntrustedError = _errors.GuardSyncEndpointUntrustedError
GuardSyncNotAvailableError = _errors.GuardSyncNotAvailableError
GuardSyncNotConfiguredError = _errors.GuardSyncNotConfiguredError

_canonical_policy_enforcement_enabled = _identity._canonical_policy_enforcement_enabled
_canonical_policy_rollout_percentage = _identity._canonical_policy_rollout_percentage
_computed_policy_bundle_hash = _identity._computed_policy_bundle_hash
_hol_guard_runtime_package_identity = _identity._hol_guard_runtime_package_identity
_hol_guard_runtime_source_sha256 = _identity._hol_guard_runtime_source_sha256
detect_harness = _identity.detect_harness
evaluate_detection = _identity.evaluate_detection
get_adapter = _identity.get_adapter

_append_authority_evidence_to_receipts = _authority._append_authority_evidence_to_receipts
_config_with_current_authority = _authority._config_with_current_authority
_get_default_detector_registry = _authority._get_default_detector_registry
_guard_sync_auth_lock = _authority._guard_sync_auth_lock
_normalized_runtime_detector_telemetry = _authority._normalized_runtime_detector_telemetry
_receipt_rowid_cursor = _authority._receipt_rowid_cursor
_resolved_exact_request_overrides = _authority._resolved_exact_request_overrides
_resolved_interactive_request_overrides = _authority._resolved_interactive_request_overrides
_runtime_detector_authority = _authority._runtime_detector_authority
_runtime_detector_context = _authority._runtime_detector_context
_runtime_detector_nonterminal_evidence = _authority._runtime_detector_nonterminal_evidence
_saved_decision_is_retained = _authority._saved_decision_is_retained

_GuardRunLaunchPlan = _launch._GuardRunLaunchPlan
_complete_guard_run_launch = _launch._complete_guard_run_launch
_guard_run_authority_signature = _launch._guard_run_authority_signature
_guard_run_executable_prefix = _launch._guard_run_executable_prefix
_guard_run_finalize_authorized_launch_plan = _launch._guard_run_finalize_authorized_launch_plan
_guard_run_launch_environment = _launch._guard_run_launch_environment
_guard_run_launch_environment_hash = _launch._guard_run_launch_environment_hash
_guard_run_launch_plan_signature = _launch._guard_run_launch_plan_signature
_guard_run_launch_previews = _launch._guard_run_launch_previews
_guard_run_plan_for_command = _launch._guard_run_plan_for_command
_resolve_hermes_guard_access_token = _launch._resolve_hermes_guard_access_token

_first_match = _prompt_intent._first_match
_following_sentence_has_secret_read_intent = _prompt_intent._following_sentence_has_secret_read_intent
_iter_hint_occurrences = _prompt_intent._iter_hint_occurrences
_next_non_whitespace_character = _prompt_intent._next_non_whitespace_character
_previous_non_whitespace_character = _prompt_intent._previous_non_whitespace_character
_prompt_has_secret_read_intent = _prompt_intent._prompt_has_secret_read_intent
_prompt_match_is_documented_example = _prompt_intent._prompt_match_is_documented_example
_prompt_match_is_wrapped_literal = _prompt_intent._prompt_match_is_wrapped_literal
_prompt_secret_intent_region = _prompt_intent._prompt_secret_intent_region
_prompt_sentence_end = _prompt_intent._prompt_sentence_end
_prompt_sentence_start = _prompt_intent._prompt_sentence_start
_secret_match_sentence = _prompt_intent._secret_match_sentence
_secret_read_intent_is_negated = _prompt_intent._secret_read_intent_is_negated

guard_run = _execution.guard_run

_artifact_with_authority_updates = _detector_evaluation._artifact_with_authority_updates
_evaluation_with_action_envelope = _detector_evaluation._evaluation_with_action_envelope
_evaluation_with_claim_context_failure = _detector_evaluation._evaluation_with_claim_context_failure
_evaluation_with_detector_registry = _detector_evaluation._evaluation_with_detector_registry
_evaluation_with_preclaim_failure = _detector_evaluation._evaluation_with_preclaim_failure
_evaluation_with_recorded_detector_result = _detector_evaluation._evaluation_with_recorded_detector_result
_guard_run_action_envelope = _detector_evaluation._guard_run_action_envelope
_runtime_detector_signals_from_evaluation = _detector_evaluation._runtime_detector_signals_from_evaluation

_detection_with_prompt_artifacts = _prompt_requests._detection_with_prompt_artifacts
_guard_run_config_paths = _prompt_requests._guard_run_config_paths
_prompt_config_candidates = _prompt_requests._prompt_config_candidates
_prompt_policy_path = _prompt_requests._prompt_policy_path
_prompt_request_id = _prompt_requests._prompt_request_id
_redact_detector_debug_payload = _prompt_requests._redact_detector_debug_payload
_write_detector_debug_trace = _prompt_requests._write_detector_debug_trace
extract_prompt_requests = _prompt_requests.extract_prompt_requests
prompt_requests_to_artifacts = _prompt_requests.prompt_requests_to_artifacts
should_force_reapproval = _prompt_requests.should_force_reapproval

_build_canonical_policy_bundle_decisions = _policy._build_canonical_policy_bundle_decisions
_build_policy_bundle_decisions = _policy._build_policy_bundle_decisions
_parse_policy_simulation_timestamp = _policy._parse_policy_simulation_timestamp
_persist_cloud_exceptions = _policy._persist_cloud_exceptions
_policy_bundle_acceptance_checkpoint = _policy._policy_bundle_acceptance_checkpoint
_policy_bundle_cloud_exception_items = _policy._policy_bundle_cloud_exception_items
_policy_bundle_downgrade_reference = _policy._policy_bundle_downgrade_reference
_policy_bundle_is_version_downgrade = _policy._policy_bundle_is_version_downgrade
_policy_bundle_numeric_version = _policy._policy_bundle_numeric_version
_policy_bundle_rejection_payload = _policy._policy_bundle_rejection_payload
_policy_bundle_utc_datetime = _policy._policy_bundle_utc_datetime
_policy_shadow_mismatch_reason_codes = _policy._policy_shadow_mismatch_reason_codes
_receipt_policy_bundle_matcher_family = _policy._receipt_policy_bundle_matcher_family
_validate_cached_policy_bundle = _policy._validate_cached_policy_bundle
simulate_policy_bundle_receipts = _policy.simulate_policy_bundle_receipts

sync_receipts = _receipt_sync.sync_receipts

_fetch_supply_chain_bundle_payload = _supply_chain._fetch_supply_chain_bundle_payload
_guard_cloud_http_error_details = _supply_chain._guard_cloud_http_error_details
_normalized_supply_chain_bundle_index_url = _supply_chain._normalized_supply_chain_bundle_index_url
_supply_chain_partition_bundle_url = _supply_chain._supply_chain_partition_bundle_url
_sync_supply_chain_bundle_incremental = _supply_chain._sync_supply_chain_bundle_incremental
sync_supply_chain_bundle = _supply_chain.sync_supply_chain_bundle

_guard_events_endpoint_unavailable_recently = _events._guard_events_endpoint_unavailable_recently
_record_guard_events_sync_failure = _events._record_guard_events_sync_failure
sync_guard_events = _events.sync_guard_events
sync_pain_signals = _events.sync_pain_signals

_check_plan_restriction_403 = _http._check_plan_restriction_403
_is_timeout_error = _http._is_timeout_error
_parse_retry_after_header = _http._parse_retry_after_header
_read_guard_cloud_error_message = _http._read_guard_cloud_error_message
_redact_sync_text = _http._redact_sync_text
_request_for_gateway_retry = _http._request_for_gateway_retry
_retry_after_sleep_seconds = _http._retry_after_sleep_seconds
_retryable_gateway_http_error = _http._retryable_gateway_http_error
_sync_http_error_message = _http._sync_http_error_message
_sync_url_error_message = _http._sync_url_error_message
_urlopen_json_with_timeout_retry = _http._urlopen_json_with_timeout_retry
_urlopen_with_sync_retries = _http._urlopen_with_sync_retries
_urlopen_with_timeout_retry = _http._urlopen_with_timeout_retry

_local_guard_runtime_session = _session_sync._local_guard_runtime_session
sync_local_guard_cloud_proof = _session_sync.sync_local_guard_cloud_proof
sync_runtime_session = _session_sync.sync_runtime_session

_base64url_encode = _dpop._base64url_encode
_dpop_access_token_confirmation_claim = _dpop._dpop_access_token_confirmation_claim
_dpop_nonce_from_http_error = _dpop._dpop_nonce_from_http_error
_encode_jwt_segment = _dpop._encode_jwt_segment
_guard_http_header_value = _dpop._guard_http_header_value
_guard_sync_headers = _dpop._guard_sync_headers
_guard_sync_request = _dpop._guard_sync_request
_guard_sync_request_with_nonce = _dpop._guard_sync_request_with_nonce
_http_error_payload = _dpop._http_error_payload
_refresh_guard_sync_request = _dpop._refresh_guard_sync_request
_remember_guard_dpop_request_context = _dpop._remember_guard_dpop_request_context
_resolve_guard_dpop_retry_context = _dpop._resolve_guard_dpop_retry_context
_sign_guard_dpop_proof = _dpop._sign_guard_dpop_proof

_guard_oauth_reauthorization_message = _oauth_repair._guard_oauth_reauthorization_message
_guard_oauth_reconnect_after_revoked_message = _oauth_repair._guard_oauth_reconnect_after_revoked_message
_guard_runtime_upgrade_restart_message = _oauth_repair._guard_runtime_upgrade_restart_message
_guard_runtime_was_upgraded = _oauth_repair._guard_runtime_was_upgraded
_guard_sync_reconnect_message = _oauth_repair._guard_sync_reconnect_message
_invalid_grant_oauth_error_details = _oauth_repair._invalid_grant_oauth_error_details
_invalid_grant_oauth_payload = _oauth_repair._invalid_grant_oauth_payload
_oauth_authorization_error_requires_fresh_sign_in = _oauth_repair._oauth_authorization_error_requires_fresh_sign_in
_oauth_refresh_error_message = _oauth_repair._oauth_refresh_error_message
_validate_guard_sync_url = _oauth_repair._validate_guard_sync_url
clear_revoked_guard_oauth_sign_in = _oauth_repair.clear_revoked_guard_oauth_sign_in
prepare_guard_cloud_connect_authorization = _oauth_repair.prepare_guard_cloud_connect_authorization
repair_guard_cloud_connect_storage = _oauth_repair.repair_guard_cloud_connect_storage

_cached_oauth_access_token = _oauth_refresh._cached_oauth_access_token
_oauth_access_token_expires_at = _oauth_refresh._oauth_access_token_expires_at
_oauth_dpop_key_material = _oauth_refresh._oauth_dpop_key_material
_oauth_sync_url_from_issuer = _oauth_refresh._oauth_sync_url_from_issuer
_persist_recovered_oauth_binding = _oauth_refresh._persist_recovered_oauth_binding
_persist_rotated_oauth_refresh_token = _oauth_refresh._persist_rotated_oauth_refresh_token
_refresh_guard_oauth_access_token = _oauth_refresh._refresh_guard_oauth_access_token
_refresh_guard_oauth_access_token_once = _oauth_refresh._refresh_guard_oauth_access_token_once

_apply_refreshed_oauth_credentials = _oauth_context._apply_refreshed_oauth_credentials
_resolve_guard_sync_auth_context = _oauth_context._resolve_guard_sync_auth_context
_resolve_guard_sync_auth_context_from_oauth_credentials = (
    _oauth_context._resolve_guard_sync_auth_context_from_oauth_credentials
)
_test_sync_auth_context_from_env = _oauth_context._test_sync_auth_context_from_env

_auth_context_sync_url = _payload_fields._auth_context_sync_url
_extract_dict_field = _payload_fields._extract_dict_field
_guard_events_sync_url = _payload_fields._guard_events_sync_url
_int_value = _payload_fields._int_value
_last_uploaded_event_id = _payload_fields._last_uploaded_event_id
_metric_count = _payload_fields._metric_count
_normalized_receipts_sync_url = _payload_fields._normalized_receipts_sync_url
_normalized_runtime_sessions_sync_url = _payload_fields._normalized_runtime_sessions_sync_url
_normalized_supply_chain_bundle_url = _payload_fields._normalized_supply_chain_bundle_url
_normalized_timestamp_string = _payload_fields._normalized_timestamp_string
_now = _payload_fields._now
_optional_string = _payload_fields._optional_string
_pain_signal_sync_url = _payload_fields._pain_signal_sync_url
_parse_iso_timestamp = _payload_fields._parse_iso_timestamp
_remote_harness = _payload_fields._remote_harness
_remote_workspace = _payload_fields._remote_workspace
_request_data_bytes = _payload_fields._request_data_bytes
_string_items = _payload_fields._string_items
_sync_timestamp = _payload_fields._sync_timestamp

_artifact_type_for_signal = _metrics._artifact_type_for_signal
_build_value_metrics = _metrics._build_value_metrics
_build_weekly_firewall_digest = _metrics._build_weekly_firewall_digest
_pain_signal_artifact_identity = _metrics._pain_signal_artifact_identity
_pain_signal_item = _metrics._pain_signal_item
_pain_signal_summary = _metrics._pain_signal_summary
_record_synced_alert_events = _metrics._record_synced_alert_events
_should_emit_pain_signal = _metrics._should_emit_pain_signal
_warning_occurrence_key = _metrics._warning_occurrence_key

_advance_command_detail_backfill_marker = _receipt_cursor._advance_command_detail_backfill_marker
_cloud_sync_receipts_payload = _receipt_cursor._cloud_sync_receipts_payload
_completed_guard_event_ids = _receipt_cursor._completed_guard_event_ids
_dedupe_sync_payload_items = _receipt_cursor._dedupe_sync_payload_items
_iter_receipt_sync_batches = _receipt_cursor._iter_receipt_sync_batches
_persist_receipt_sync_cursor = _receipt_cursor._persist_receipt_sync_cursor
_receipt_command_detail_backfill_before_rowid = _receipt_cursor._receipt_command_detail_backfill_before_rowid
_receipt_sync_context = _receipt_cursor._receipt_sync_context
_receipt_sync_cursor_rowid = _receipt_cursor._receipt_sync_cursor_rowid
_receipt_sync_cursor_rowids_from_batch = _receipt_cursor._receipt_sync_cursor_rowids_from_batch
_receipt_sync_rows_for_upload = _receipt_cursor._receipt_sync_rows_for_upload
_receipt_sync_rows_with_command_detail_backfill = _receipt_cursor._receipt_sync_rows_with_command_detail_backfill
_validated_policy_bundle_acknowledgement = _receipt_cursor._validated_policy_bundle_acknowledgement

_cloud_sync_artifact_slug = _receipt_privacy._cloud_sync_artifact_slug
_cloud_sync_artifact_type = _receipt_privacy._cloud_sync_artifact_type
_cloud_sync_command_display_part = _receipt_privacy._cloud_sync_command_display_part
_cloud_sync_receipt_action_command = _receipt_privacy._cloud_sync_receipt_action_command
_cloud_sync_receipt_fingerprint = _receipt_privacy._cloud_sync_receipt_fingerprint
_cloud_sync_receipt_payload = _receipt_privacy._cloud_sync_receipt_payload
_cloud_sync_recommendation = _receipt_privacy._cloud_sync_recommendation
_cloud_sync_sanitize_text = _receipt_privacy._cloud_sync_sanitize_text
_cloud_sync_transport_encode_text = _receipt_privacy._cloud_sync_transport_encode_text
_ensure_cloud_review_privacy_projection = _receipt_privacy._ensure_cloud_review_privacy_projection
_ensure_relaxed_receipt_redaction_resync = _receipt_privacy._ensure_relaxed_receipt_redaction_resync
_looks_like_source_excerpt = _receipt_privacy._looks_like_source_excerpt
_persist_cloud_receipt_redaction_level = _receipt_privacy._persist_cloud_receipt_redaction_level
_receipt_redaction_level_rank = _receipt_privacy._receipt_redaction_level_rank
_requeue_cloud_review_privacy_projection = _receipt_privacy._requeue_cloud_review_privacy_projection
_reset_cloud_receipt_redaction_authority = _receipt_privacy._reset_cloud_receipt_redaction_authority
_resolve_cloud_receipt_redaction_level = _receipt_privacy._resolve_cloud_receipt_redaction_level
_stored_cloud_receipt_redaction_level = _receipt_privacy._stored_cloud_receipt_redaction_level

_cloud_local_identity_payload = _session_payload._cloud_local_identity_payload
_cloud_local_identity_source_payload = _session_payload._cloud_local_identity_source_payload
_cloud_package_manager_coverage = _session_payload._cloud_package_manager_coverage
_cloud_runtime_session_payload = _session_payload._cloud_runtime_session_payload
_guard_device_metadata = _session_payload._guard_device_metadata
_safe_hostname = _session_payload._safe_hostname
_safe_private_ip = _session_payload._safe_private_ip
_safe_private_ipv6 = _session_payload._safe_private_ipv6
_sync_extension_catalog_from_runtime_handshake = _session_payload._sync_extension_catalog_from_runtime_handshake

_activate_receipt_sync_policy = _receipt_policy._activate_receipt_sync_policy

_LOADED_HOL_GUARD_RUNTIME_PACKAGE_IDENTITY = _hol_guard_runtime_package_identity()


_DEFAULT_DETECTOR_REGISTRY: tuple[Callable[[], tuple[Any, ...]], DetectorRegistry] | None = None


_DEFAULT_DETECTOR_REGISTRY_LOCK = threading.Lock()


_GUARD_DPOP_REQUEST_CONTEXTS: dict[str, dict[str, object]] = {}


_oauth_binding_metadata_from_access_token = oauth_binding_from_credentials


# Test-only override: when set, _resolve_guard_sync_auth_context returns this dict
# directly instead of resolving OAuth credentials (which would refresh tokens over
# the network). Tests seed OAuth credentials for status/connect-state checks and set
# this override to keep sync-path exercises hermetic.
_test_sync_auth_context_override: dict[str, object] | None = None
