//! Static Cline tool/event/key tables.

pub(crate) const EVENT_NAMES: &[(&str, &str)] = &[
    ("pretooluse", "PreToolUse"),
    ("pretool", "PreToolUse"),
    ("tool_call", "PreToolUse"),
    ("toolcall", "PreToolUse"),
    ("posttooluse", "PostToolUse"),
    ("posttool", "PostToolUse"),
    ("tool_result", "PostToolUse"),
    ("toolresult", "PostToolUse"),
    ("userpromptsubmit", "UserPromptSubmit"),
    ("prompt_submit", "UserPromptSubmit"),
    ("promptsubmit", "UserPromptSubmit"),
    ("taskstart", "TaskStart"),
    ("agent_start", "TaskStart"),
    ("taskresume", "TaskResume"),
    ("agent_resume", "TaskResume"),
    ("taskcomplete", "TaskComplete"),
    ("agent_end", "TaskComplete"),
    ("taskcancel", "TaskCancel"),
    ("agent_abort", "TaskCancel"),
    ("taskerror", "TaskError"),
    ("agent_error", "TaskError"),
    ("sessionshutdown", "SessionShutdown"),
    ("session_shutdown", "SessionShutdown"),
    ("precompact", "PreCompact"),
];

pub(crate) const SHELL_TOOLS: &[&str] = &[
    "run_commands",
    "run_command",
    "execute_command",
    "execute_command_line",
    "terminal",
    "bash",
    "shell",
];
pub(crate) const READ_TOOLS: &[&str] = &[
    "read_files",
    "read_file",
    "read",
    "view_file",
    "open_file",
    "cat_file",
    "search_files",
    "list_files",
    "list_code_definition_names",
    "grep",
    "rg",
];
pub(crate) const WRITE_TOOLS: &[&str] = &[
    "editor",
    "edit_file",
    "write_file",
    "write_to_file",
    "replace_in_file",
    "apply_patch",
    "patch",
];
pub(crate) const NETWORK_TOOLS: &[&str] = &[
    "fetch_web_content",
    "web_fetch",
    "web_search",
    "browser",
    "browser_action",
    "open_url",
    "visit_url",
];
pub(crate) const MCP_TOOLS: &[&str] = &[
    "use_mcp_tool",
    "access_mcp_resource",
    "mcp_tool",
    "mcp_resource",
];
pub(crate) const ACTION_BEARING_KEYS: &[&str] = &[
    "command",
    "commands",
    "cmd",
    "path",
    "paths",
    "file",
    "files",
    "file_path",
    "file_paths",
    "patch",
    "url",
    "urls",
    "uri",
    "href",
    "server",
    "server_name",
    "servername",
    "tool",
    "tool_name",
    "toolname",
    "package",
    "packages",
    "executable",
];
pub(crate) const PATH_KEYS: &[&str] = &[
    "path",
    "paths",
    "file",
    "files",
    "file_path",
    "file_paths",
    "filepath",
    "filepaths",
    "target_path",
    "target_paths",
];
