//! Audited identities, not a count of fully qualified semantic translations.

pub fn compatibility_rule_ids() -> &'static [&'static str] {
    &[
        "command.container-runtime.docker-sensitive",
        "command.container-runtime.docker-config-access",
        "command.data-protection.credential-exfiltration",
        "command.data-protection.file-upload",
        "command.git.unverified-fetch",
        "command.git.index-inspection",
        "command.git.branch",
        "command.git.pull",
        "command.git.push",
        "command.git.clone",
        "command.git.fetch",
        "command.git.remote",
        "command.git.status",
        "command.git.log",
        "command.git.diff",
        "command.git.show",
        "command.git.blame",
        "command.git.grep",
        "command.git.describe",
        "command.git.ls-files",
        "command.git.reflog",
        "command.github.routine-merge",
        "command.github.workflow-mutation",
        "command.github.local-write",
        "command.github.maintenance",
        "command.github.content",
        "command.github.merge",
        "command.github.admin-merge",
        "command.github.publish",
        "command.github.workflow",
        "command.github.force",
        "command.github.delete",
        "command.github.secret",
        "command.github.access",
        "command.github.mutation",
        "command.github.unknown",
        "command.kubernetes-secrets.secret-read",
        "command.shell-mutations.destructive-shell",
        "command.shell-mutations.managed-config-write",
        "command.shell-mutations.sensitive-file-write",
        "command.shell-mutations.process-environment-secret-read",
        "command.shell-mutations.github-body-substitution",
    ]
}

pub(super) fn github_owner(capability: &str) -> (&'static str, bool) {
    match capability {
        "read_local" => ("command.github.permission.read-local", true),
        "read_remote" => ("command.github.permission.read-remote", true),
        "propose_remote" => ("command.github.permission.propose-remote", true),
        "routine_review_thread_remote" => (
            "command.github.permission.routine-review-thread-remote",
            true,
        ),
        "routine_merge_remote" => ("command.github.routine-merge", false),
        "routine_workflow_remote" => ("command.github.workflow-mutation", false),
        "write_local" => ("command.github.local-write", false),
        "maintain_remote" => ("command.github.maintenance", false),
        "content_remote" => ("command.github.content", false),
        "merge_remote" => ("command.github.merge", false),
        "admin_merge_remote" => ("command.github.admin-merge", false),
        "publish_remote" => ("command.github.publish", false),
        "workflow_remote" => ("command.github.workflow", false),
        "force_remote" => ("command.github.force", false),
        "delete_remote" => ("command.github.delete", false),
        "secret_remote" => ("command.github.secret", false),
        "access_remote" => ("command.github.access", false),
        "mutate_remote" => ("command.github.mutation", false),
        _ => ("command.github.unknown", false),
    }
}
