"""Publish current-build directory bytes without committing generated source files.

The portal accepts this file only from a successful canonical main CI run at
its exact current SHA. Stable descriptor identities preserve existing profiles.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REPOSITORY = "hashgraph-online/hol-guard"
REPOSITORY_ID = 1194748811
SCHEMA = "guard.extension-directory-build.v1"
MAX_FRAME_BYTES = 4 * 1024 * 1024
OUTPUT = ROOT / "build/public-directory/guard-extension-directory.json"


def build_frame(directory: dict, *, root: Path, source_sha: str, run_id: int, run_attempt: int) -> dict:
    """Bind public metadata and exact generated bytes to one source build."""
    from codex_plugin_scanner.guard.extension_builder.io import read_bytes

    if not re.fullmatch(r"[0-9a-f]{40}", source_sha):
        raise ValueError("directory build requires a full source SHA")
    if type(run_id) is not int or type(run_attempt) is not int or not 0 < run_id < 2**53 or not 0 < run_attempt < 2**31:
        raise ValueError("directory build requires positive run identity and attempt")
    if directory.get("schemaVersion") != "guard.extension-directory.v2":
        raise ValueError("directory build requires the source-aware v2 contract")
    generated: dict[str, str] = {}
    entries = directory.get("entries")
    if not isinstance(entries, list) or not 0 < len(entries) <= 512:
        raise ValueError("directory inventory is invalid")
    for entry in entries:
        identity = entry["id"]
        source_path = entry["sourcePath"]
        if entry["kind"] != "command":
            continue
        if source_path != f"contributions/extensions/{identity}.json" or not re.fullmatch(
            r"command\.[a-z0-9.-]+", identity
        ):
            raise ValueError("generated descriptor path does not match its public identity")
        if source_path in generated:
            raise ValueError("duplicate generated descriptor")
        content = read_bytes(root / source_path, limit=1_048_576)
        if "sha256:" + hashlib.sha256(content).hexdigest() != entry["contributionDigest"]:
            raise ValueError("generated descriptor changed during directory export")
        authored = entry["authoringSource"]
        if authored["path"] != f"contributions/command-sources/{identity}.json":
            raise ValueError("authored source path does not match its descriptor")
        source = read_bytes(root / authored["path"], limit=1_048_576)
        if "sha256:" + hashlib.sha256(source).hexdigest() != authored["byteDigest"]:
            raise ValueError("authored source changed during directory export")
        generated[source_path] = content.decode("utf-8")
    frame = {
        "schemaVersion": SCHEMA,
        "repository": REPOSITORY,
        "repositoryId": REPOSITORY_ID,
        "sourceSha": source_sha,
        "runId": run_id,
        "runAttempt": run_attempt,
        "directory": directory,
        "generatedSources": generated,
    }
    if len(encode_frame(frame)) > MAX_FRAME_BYTES:
        raise ValueError("directory build output exceeds its byte budget")
    return frame


def encode_frame(frame: dict) -> bytes:
    """Use deterministic JSON with no local paths or volatile measurements."""
    return (
        json.dumps(frame, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False) + "\n"
    ).encode()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-sha", required=True)
    parser.add_argument("--run-id", type=int, required=True)
    parser.add_argument("--run-attempt", type=int, required=True)
    args = parser.parse_args()
    sys.path[:0] = [str(ROOT), str(ROOT / "src")]
    from scripts.build_guard_resources import _atomic_write, current_manifest
    from scripts.export_extension_directory import export_directory_v2

    if current_manifest(ROOT) is None:
        parser.error("directory requires complete, current, verified build resources")
    head = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True, timeout=30).strip()
    if head != args.source_sha:
        parser.error("directory source SHA does not match the checked-out tree")
    subprocess.run(["git", "diff", "--exit-code", "HEAD", "--"], cwd=ROOT, check=True, timeout=30)
    frame = build_frame(
        export_directory_v2(), root=ROOT, source_sha=head, run_id=args.run_id, run_attempt=args.run_attempt
    )
    subprocess.run(["git", "diff", "--exit-code", "HEAD", "--"], cwd=ROOT, check=True, timeout=30)
    _atomic_write(ROOT, OUTPUT, encode_frame(frame))
    print(json.dumps({"ok": True, "entries": len(frame["directory"]["entries"]), "source_sha": head}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
