from pathlib import Path
import ast
src=Path.cwd()/'src/codex_plugin_scanner/guard'
docs={
'_snake_to_camel_case_key':'Translate a Python field name to the inventory wire key.',
'_normalize_redaction_report':'Validate and normalize redaction counts into the public report shape.',
'_normalize_inventory_datetime':'Serialize a valid inventory timestamp consistently in UTC.',
'_inventory_contract_json':'Serialize contract data through the established field-name and safety rules.',
'serialize_inventory_snapshot':'Emit the inventory wire contract after applying final redaction checks.',
'inventory_snapshot_from_detection':'Assemble native artifacts, scanner findings, and trust evidence into one snapshot.',
'fingerprint_text':'Hash UTF-8 text using the inventory content-identity algorithm.',
'fingerprint_mapping':'Hash a mapping after deterministic JSON serialization.',
'_inventory_snapshot_content_hash':'Compute snapshot identity from stable evidence rather than observation timestamps.',
'_stable_snapshot_value':'Remove volatile fields before calculating a repeatable snapshot fingerprint.',
'_stable_snapshot_sort_key':'Build a deterministic key for ordering stable snapshot values.',
'inventory_item_id':'Build a stable item identifier from harness, source, and artifact identity.',
'fingerprint_path_tree':'Fingerprint a bounded set of files without following untrusted path traversal.',
'_fingerprint_file_bytes':'Read bounded file content for fingerprinting within the permitted inspection roots.',
'_item_from_artifact':'Convert a native artifact into an inventory item with source and trust metadata.',
'_mcp_tool_items_from_artifact':'Expand advertised MCP tool definitions into individually attributable inventory items.',
'_apply_tool_trust_attestation_metadata':'Attach tool-level trust metadata only when compatible attestation evidence exists.',
'_attestation_path_hash':'Hash an attestation path without exporting the private absolute path.',
'_attestation_repository_id':'Resolve repository identity from the available artifact metadata.',
'_optional_context_string':'Read a nonempty optional string from an untrusted metadata context.',
'_string_value':'Normalize an optional metadata value to a safe string.',
'_first_present_value':'Select the first available metadata value in precedence order.',
'_mcp_tool_definitions':'Read supported MCP definition shapes without treating arbitrary metadata as tools.',
'_mcp_schema_signal_text':'Extract textual signals from a tool schema for capability classification.',
'_capabilities_for_mcp_tool':'Classify tool capabilities from its advertised name, description, and schema.',
'_risk_level_for_capabilities':'Derive the inventory risk category from the classified capabilities.',
'_aibom_detection_module':'Load source-of-truth detection lazily to avoid inventory initialization cycles.',
'_aibom_symlink_module':'Load symlink evidence helpers only when inventory enrichment requires them.',
'_aibom_trust_metadata_module':'Load trust metadata enrichment without eagerly initializing its dependencies.',
'_inventory_item_description_module':'Load native item description helpers through their existing module interface.',
'_item_kind':'Map a native artifact category to the inventory item-kind contract.',
'_resolve_item_content_hash':'Choose a verified content hash from supported artifact evidence.',
'_discard_unverified_skill_directory_hash':'Remove a directory hash when its content cannot be verified safely.',
'_primary_artifact_content_hash':'Read the primary artifact fingerprint without substituting unrelated evidence.',
'_canonical_inventory_content_hash':'Normalize a supported content fingerprint into its canonical wire form.',
'_safe_roots_for_inspection':'Derive bounded filesystem roots permitted for source-of-truth inspection.',
'_apply_source_of_truth_metadata':'Reconcile metadata with the native source while retaining bounded inspection.',
'_apply_aibom_metadata_enrichment':'Add inventory detection, symlink, and trust evidence through established helpers.',
'_capabilities_for_artifact':'Classify native artifact capabilities from supported metadata and findings.',
'_bind_skill_document_evidence':'Bind skill document identity and content evidence to its inventory item.',
'_risk_level':'Normalize a scanner severity to a supported inventory risk level.',
'redact_local_path':'Replace private absolute path prefixes while preserving useful relative identity.',
'redact_headers':'Preserve header names while redacting credential-bearing header values.',
'redact_url':'Remove sensitive URL credentials and query values before exporting an endpoint.',
'classify_endpoint_host':'Classify an endpoint host without making a network request.',
'_safe_source_detail':'Redact source descriptions and record the resulting redaction counts.',
'_safe_finding_text':'Sanitize finding text without exposing private paths or credential values.',
'_safe_artifact_metadata':'Restrict exported artifact metadata to supported fields and sanitized values.',
'_sanitize_paths':'Recursively sanitize private path values in supported metadata structures.',
'_redact_known_path':'Redact one known local path using the operator home boundary.',
'_redact_command_value':'Redact path and credential values from an exported command string.',
'_sanitize_serializer_string':'Apply final string redaction before inventory serialization.',
'_assert_serialized_inventory_payload_safe':'Reject serialized inventory that still violates the export safety contract.',
'_safe_json':'Normalize metadata into bounded JSON-compatible evidence.',
'_cisco_inventory_findings':'Map optional scanner findings into the canonical inventory finding contract.',
'_cisco_inventory_sources':'Record scanner sources and their availability alongside inventory evidence.',
'_cisco_source':'Build a source descriptor for one supported scanner.',
'_inventory_severity':'Normalize scanner severity without elevating unknown values.',
'_score_delta_for_severity':'Map a finding severity to the established inventory score adjustment.',
'_artifact_id_for_cisco_finding':'Associate a scanner finding with a known native artifact when possible.',
'_source_status_for_cisco_status':'Map scanner completion state to the public inventory source status.',
'_symlink_findings_from_items':'Convert recorded symlink evidence into attributable inventory findings.',
}
for p in sorted(src.glob('inventory_contract*.py')):
 text=p.read_text();lines=text.splitlines(keepends=True);edits=[]
 for node in ast.walk(ast.parse(text)):
  if isinstance(node,ast.FunctionDef) and not ast.get_docstring(node):
   if node.name not in docs:raise RuntimeError(node.name)
   edits.append((node.body[0].lineno-1,' '*(node.col_offset+4)+'"""'+docs[node.name]+'"""\n'))
 for at,line in sorted(edits,reverse=True):lines.insert(at,line)
 p.write_text(''.join(lines))
