"""Structural dependencies kept live by the Guard render facade."""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import pathlib
    import re
    from collections.abc import Callable, Sequence
    from types import ModuleType

    from rich.box import Box

    from ..redaction import RedactedText
    from . import render as _render_types


class RenderBox(Protocol):
    SIMPLE_HEAD: Box
    SIMPLE_HEAVY: Box


class RenderContext(Protocol):
    Console: type[_render_types.Console]
    Panel: type[_render_types.Panel]
    Path: type[pathlib.Path]
    Syntax: type[_render_types.Syntax]
    Table: type[_render_types.Table]
    Text: type[_render_types.Text]
    box: RenderBox
    json: ModuleType
    re: ModuleType
    sys: ModuleType
    textwrap: ModuleType
    _JSON_RENDERERS: dict[str, Callable[[_render_types.PayloadDict], _render_types.PayloadDict]]
    _KNOWN_MANAGED_INSTALL_MODES: dict[str, str]
    _MODE_ACRONYMS: frozenset[str]
    _NON_SECRET_DIAGNOSTIC_KEYS: frozenset[str]
    _NON_SECRET_STRUCTURED_KEYS: frozenset[str]
    _PLAIN_TEXT_RENDERERS: dict[str, _render_types.PlainTextRenderer]
    _RENDERERS: dict[str, _render_types.Renderer]
    _RICH_AVAILABLE: bool
    _SAFE_POLICY_LITERALS: frozenset[str]
    _SENSITIVE_KEY_TOKENS: tuple[str, ...]
    _SENSITIVE_STRING_PATTERNS: tuple[tuple[re.Pattern[str], str], ...]
    _SEVERITY_COLORS: dict[str, str]
    _TRUST_SENSITIVE_STRING_PATTERNS: tuple[tuple[re.Pattern[str], str], ...]

    def _redact_payload(self, value: object, *, key: str | None = None, command: str | None = None) -> object: ...

    def _render_redacted_json_payload(self, redacted_payload: object) -> str: ...

    def _safe_json_output_text(self, command: str, payload: _render_types.PayloadDict) -> str: ...

    def _sanitize_payload_for_output(self, value: object, *, command: str | None = None) -> object: ...

    def _json_payload_for_command(
        self, command: str, payload: _render_types.PayloadDict
    ) -> _render_types.PayloadDict: ...

    def _serialize_redacted_json(self, value: object, *, indent: int) -> str: ...

    def _init_plan_panel(self, plan: list[dict[str, object]], status: str) -> _render_types.Panel: ...

    def _init_decision_label(self, decision: str) -> str: ...

    def _init_panel_title(self, status: str) -> str: ...

    def _init_skip_reason(self, payload: dict[str, object]) -> str: ...

    def _init_dashboard_summary(self, payload: dict[str, object]) -> str: ...

    def _init_apps_summary(self, payload: dict[str, object], count: int) -> str: ...

    def _init_cloud_summary(self, payload: dict[str, object]) -> str: ...

    def _init_notification_summary(self, payload: dict[str, object]) -> str: ...

    def _protection_display_name(self, payload: dict[str, object], fallback: str) -> str: ...

    def _protection_status_copy(self, payload: dict[str, object], fallback: str) -> tuple[str, bool]: ...

    def _bootstrap_install_summary(self, bootstrap_install: object, *, fallback_harness: str) -> str: ...

    def _build_trust_doctor_panel(self, trust: dict[str, object]) -> _render_types.Panel: ...

    def _build_advisory_table(
        self, items: list[dict[str, object]], *, title: str | None = None
    ) -> _render_types.Table: ...

    def _render_managed_install(self, console: _render_types.Console, payload: dict[str, object]) -> None: ...

    def _render_supply_chain_risk_results(
        self,
        console: _render_types.Console,
        supply_chain_risks: list[dict[str, object]],
    ) -> None: ...

    def _render_safe_decode_results(
        self,
        console: _render_types.Console,
        safe_decode_risks: list[dict[str, object]],
    ) -> None: ...

    def _render_sandbox_results(
        self,
        console: _render_types.Console,
        sandbox_analysis: list[dict[str, object]],
    ) -> None: ...

    def _render_skill_scan_results(
        self, console: _render_types.Console, skill_scan: list[dict[str, object]]
    ) -> None: ...

    def _managed_install_workspace_label(self, workspace: object) -> str: ...

    def _managed_install_config_label(self, manifest: dict[str, object]) -> str: ...

    def _render_single_managed_install(
        self,
        console: _render_types.Console,
        managed_install: dict[str, object],
    ) -> None: ...

    def _managed_install_batch_summary(
        self,
        payload: dict[str, object],
        managed_installs: list[dict[str, object]],
    ) -> _render_types.Table: ...

    def _managed_install_batch_table(self, managed_installs: list[dict[str, object]]) -> _render_types.Table: ...

    def _managed_install_batch_notes(self, managed_installs: list[dict[str, object]]) -> list[str]: ...

    def _notes_panel(self, notes: list[str]) -> _render_types.Panel: ...

    def _managed_install_state_text(self, managed_install: dict[str, object]) -> str: ...

    def _build_ecosystem_support_table(self, items: list[dict[str, object]]) -> _render_types.Table: ...

    def _managed_install_mode_text(self, mode: object) -> str | None: ...

    def _managed_install_notes(self, managed_install: dict[str, object], manifest: object) -> list[str]: ...

    def _add_update_version_rows(self, body: _render_types.Table, version_check: object) -> None: ...

    def _connect_status_text(self, payload: dict[str, object]) -> str: ...

    def _connect_milestone_text(self, payload: dict[str, object]) -> str: ...

    def _connect_reason_text(self, payload: dict[str, object]) -> str: ...

    def _connect_reason_requires_login(self, reason: str) -> bool: ...

    def _connect_reason_requires_paid_plan(self, reason: str) -> bool: ...

    def _connect_sync_note_text(self, payload: dict[str, object]) -> str | None: ...

    def _cisco_status_text(self, status: str) -> _render_types.Text: ...

    def _render_cisco_evidence(self, console: _render_types.Console, payload: dict[str, object]) -> None: ...

    def _build_consumer_summary_table(self, payload: dict[str, object]) -> _render_types.Table: ...

    def _render_consumer_evidence_panels(self, console: _render_types.Console, payload: dict[str, object]) -> None: ...

    def _render_fallback(self, console: _render_types.Console, payload: dict[str, object]) -> None: ...

    def _build_supply_chain_posture_panel(self, supply_chain: dict[str, object]) -> _render_types.Panel: ...

    def _build_harness_table(self, detections: list[dict[str, object]]) -> _render_types.Table: ...

    def _build_product_table(self, harnesses: list[dict[str, object]]) -> _render_types.Table: ...

    def _next_action_label(self, harness: dict[str, object]) -> str: ...

    def _build_steps_panel(self, steps: Sequence[_render_types.PayloadMapping]) -> _render_types.Panel: ...

    def _build_diagnostic_command_panel(
        self,
    ) -> _render_types.Panel: ...

    def _render_harness_detail(self, console: _render_types.Console, detection: dict[str, object]) -> None: ...

    def _build_artifact_table(self, artifacts: list[dict[str, object]]) -> _render_types.Table: ...

    def _build_artifact_result_table(self, artifacts: list[dict[str, object]]) -> _render_types.Table: ...

    def _build_run_artifact_table(self, artifacts: list[dict[str, str]]) -> _render_types.Table: ...

    def _run_title(self, *, blocked: bool, dry_run: bool) -> str: ...

    def _run_outcome_text(self, *, blocked: bool, dry_run: bool, launched: bool) -> str: ...

    def _build_run_steps(self, payload: dict[str, object], *, blocked: bool, dry_run: bool) -> list[dict[str, str]]: ...

    def _summarize_run_artifacts(self, artifacts: list[dict[str, object]]) -> list[dict[str, str]]: ...

    def _find_replaced_artifact_partner(
        self,
        artifacts: list[dict[str, object]],
        index: int,
        used_indexes: set[int],
    ) -> int | None: ...

    def _replacement_pair(
        self,
        first: dict[str, object],
        second: dict[str, object],
    ) -> tuple[dict[str, object], dict[str, object]]: ...

    def _artifact_display_name(self, artifact: dict[str, object]) -> str: ...

    def _artifact_replacement_identity(self, artifact: dict[str, object]) -> tuple[tuple[str, str], ...]: ...

    def _artifact_change_summary(self, artifact: dict[str, object]) -> str: ...

    def _field_label(self, field: str) -> str: ...

    def _artifact_reason_text(self, artifact: dict[str, object]) -> str: ...

    def _artifact_risk_text(self, *artifacts: dict[str, object]) -> str: ...

    def _run_artifact_should_be_visible(self, artifact: dict[str, object]) -> bool: ...

    def _artifact_needs_review(self, artifact: dict[str, object]) -> bool: ...

    def _build_approval_table(self, items: list[dict[str, object]], *, title: str | None) -> _render_types.Table: ...

    def _build_runtime_probe_panel(self, runtime_probe: dict[str, object]) -> _render_types.Panel: ...

    def _build_cloud_summary_panel(self, payload: dict[str, object]) -> _render_types.Panel: ...

    def _cloud_border_style(self, cloud_state: str) -> str: ...

    def _artifact_source_text(self, artifact: dict[str, object]) -> str: ...

    def _status_label(self, detection: dict[str, object]) -> str: ...

    def _status_text(self, detection: dict[str, object]) -> _render_types.Text: ...

    def _warning_count(self, detection: dict[str, object]) -> int: ...

    def _bool_label(self, value: bool) -> _render_types.Text: ...

    def _action_text(self, action: str) -> _render_types.Text: ...

    def _command_text(self, command: object) -> str: ...

    def _coerce_object_dict(self, value: object) -> _render_types.PayloadDict: ...

    def _coerce_dict_list(self, value: object) -> list[_render_types.PayloadDict]: ...

    def _coerce_string_list(self, value: object) -> list[str]: ...

    def _short_path(self, value: object) -> str: ...

    def _timestamp_parts(self, value: object) -> tuple[str, str]: ...

    def _clean_terminal_output(self, value: str) -> str: ...

    def _coerce_int(self, value: object) -> int: ...

    def redact_text(self, value: str) -> RedactedText: ...

    def redact_local_path(self, value: str, *, home_dir: pathlib.Path | None = None) -> str: ...

    def render_self_uninstall(self, console: _render_types.Console, payload: dict[str, object]) -> None: ...

    def render_sync_summary(self, console: _render_types.Console, payload: dict[str, object]) -> None: ...
