use super::*;

/// Python `_canonical_utc_timestamp` + SQLite `julianday` parity grid
/// (`/tmp/rtm009_ts_oracle.json` regenerated by the session script).
/// `julianday` compared to 1e-6 abs tolerance (f64 vs CPython double both
/// IEEE-754; last-ULP differs on some inputs).
#[test]
fn python_sqlite_oracle_parity() {
    // (input, canonical, julianday_or_null, expired_vs_now)
    let rows: &[(&str, Option<&str>, Option<f64>, bool)] = &[
        (
            "2026-10-02T00:00:00+00:00",
            Some("2026-10-02T00:00:00.000000+00:00"),
            Some(2461315.5),
            true,
        ),
        (
            "2026-10-02T00:00:00Z",
            Some("2026-10-02T00:00:00.000000+00:00"),
            Some(2461315.5),
            true,
        ),
        (
            "2026-10-02 04:30:00+04:30",
            Some("2026-10-02T00:00:00.000000+00:00"),
            Some(2461315.5),
            true,
        ),
        (
            "2026-10-02",
            Some("2026-10-02T00:00:00.000000+00:00"),
            Some(2461315.5),
            true,
        ),
        (
            "2026-10-02T12:34:56.123456+00:00",
            Some("2026-10-02T12:34:56.123456+00:00"),
            Some(2461316.024260683),
            false,
        ),
        (
            "2026-10-02T12:34:56.999999Z",
            Some("2026-10-02T12:34:56.999999+00:00"),
            Some(2461316.024270822),
            false,
        ),
        (
            "1970-01-01T00:00:00+00:00",
            Some("1970-01-01T00:00:00.000000+00:00"),
            Some(2440587.5),
            true,
        ),
        (
            "2026-02-28T23:59:59+00:00",
            Some("2026-02-28T23:59:59.000000+00:00"),
            Some(2461100.499988426),
            true,
        ),
        (
            "2024-02-29T12:00:00+00:00",
            Some("2024-02-29T12:00:00.000000+00:00"),
            Some(2460370.0),
            true,
        ),
        (
            "2026-10-02T00:00:00-05:00",
            Some("2026-10-02T05:00:00.000000+00:00"),
            Some(2461315.7083333335),
            false,
        ),
        (
            "2026-10-02 12:00:00",
            Some("2026-10-02T12:00:00.000000+00:00"),
            Some(2461316.0),
            false,
        ),
        ("not-a-date", None, None, true),
        ("", None, None, true),
        ("2026-13-01T00:00:00+00:00", None, None, true),
        (
            "2026-10-02T12:00:00.5Z",
            Some("2026-10-02T12:00:00.500000+00:00"),
            Some(2461316.0000057872),
            false,
        ),
        (
            "2026-10-02T12:00:00.123+00:00",
            Some("2026-10-02T12:00:00.123000+00:00"),
            Some(2461316.0000014235),
            false,
        ),
    ];
    let now = "2026-10-02T00:00:00+00:00";
    for (input, canonical, jd, expired) in rows {
        assert_eq!(
            canonical_utc_timestamp(input).as_deref(),
            *canonical,
            "canonical {input:?}"
        );
        match jd {
            Some(want) => {
                let got = sqlite_julianday(input).unwrap_or_else(|| panic!("julianday {input:?}"));
                assert!(
                    (got - want).abs() < 1e-6,
                    "julianday {input:?}: {got} vs {want}"
                );
            }
            None => assert_eq!(sqlite_julianday(input), None, "julianday {input:?}"),
        }
        assert_eq!(
            timestamp_has_expired(input, now),
            *expired,
            "expired {input:?}"
        );
    }
}

#[test]
fn canonical_normalizes_offset_and_z() {
    assert_eq!(
        canonical_utc_timestamp("2026-10-02 04:30:00+04:30").unwrap(),
        "2026-10-02T00:00:00.000000+00:00"
    );
    assert_eq!(
        canonical_utc_timestamp("2026-10-02T12:00:00Z").unwrap(),
        "2026-10-02T12:00:00.000000+00:00"
    );
    assert_eq!(
        canonical_utc_timestamp("2026-10-02").unwrap(),
        "2026-10-02T00:00:00.000000+00:00"
    );
}

#[test]
fn expired_semantics_match_python() {
    assert!(timestamp_has_expired(
        "2026-10-02T00:00:00+00:00",
        "2026-10-02T00:00:00+00:00"
    ));
    assert!(timestamp_has_expired(
        "2026-10-01T00:00:00+00:00",
        "2026-10-02T00:00:00+00:00"
    ));
    assert!(!timestamp_has_expired(
        "2026-10-03T00:00:00+00:00",
        "2026-10-02T00:00:00+00:00"
    ));
    // Malformed → expired.
    assert!(timestamp_has_expired(
        "not-a-date",
        "2026-10-02T00:00:00+00:00"
    ));
    assert!(timestamp_has_expired("", "2026-10-02T00:00:00+00:00"));
}

/// Consumes the language-neutral `expiry-boundaries.v1.json` corpus landed
/// under `tests/fixtures/guard-expiry-boundaries/` (RM-011/RTM-006 gap-003):
/// pins `canonical_utc_timestamp`, SQLite `julianday`, and the
/// `timestamp_has_expired` `<=`/fail-closed contract against a checked-in
/// expectation record rather than a recomputed Python oracle.
#[test]
fn expiry_boundaries_fixture() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../tests/fixtures/guard-expiry-boundaries/expiry-boundaries.v1.json"
    );
    let text = std::fs::read_to_string(path).expect("expiry-boundaries fixture");
    let doc: serde_json::Value = serde_json::from_str(&text).expect("valid fixture json");

    for v in doc["canonical_utc_timestamp_vectors"].as_array().unwrap() {
        let input = v["input"].as_str().unwrap();
        let expected = v["expected"].as_str();
        assert_eq!(
            canonical_utc_timestamp(input).as_deref(),
            expected,
            "canonical {input:?}"
        );
    }

    for v in doc["julianday_vectors"].as_array().unwrap() {
        let input = v["input"].as_str().unwrap();
        match v.get("expected") {
            Some(serde_json::Value::Null) | None => {
                assert_eq!(sqlite_julianday(input), None, "julianday {input:?}")
            }
            Some(serde_json::Value::Number(want)) => {
                let got = sqlite_julianday(input).unwrap_or_else(|| panic!("julianday {input:?}"));
                assert!(
                    (got - want.as_f64().unwrap()).abs() < 1e-6,
                    "julianday {input:?}: {got} vs {want}"
                );
            }
            _ => panic!("unexpected julianday expected for {input:?}"),
        }
    }

    for v in doc["timestamp_has_expired_vectors"].as_array().unwrap() {
        let expires_at = v["expires_at"].as_str().unwrap();
        let now = v["now"].as_str().unwrap();
        let expected = v["expected"].as_bool().unwrap();
        assert_eq!(
            timestamp_has_expired(expires_at, now),
            expected,
            "{}: expires_at={expires_at:?} now={now:?}",
            v["label"].as_str().unwrap_or("")
        );
    }
}
