"""Local Guard daemon public namespace and dependency bindings."""

from __future__ import annotations

from . import server_constants as _constants
from . import server_dependencies_base as _dependencies_base
from . import server_dependencies_guard as _dependencies_guard
from . import server_dependencies_runtime as _dependencies_runtime
from . import server_dependencies_services as _dependencies_services
from . import server_handler as _handler
from . import server_helpers_cloud_sync as _helpers_cloud_sync
from . import server_helpers_guard_connect as _helpers_guard_connect
from . import server_helpers_headless as _helpers_headless
from . import server_helpers_package_connect as _helpers_package_connect
from . import server_helpers_support as _helpers_support
from . import server_helpers_values as _helpers_values
from . import server_http as _http
from . import server_service as _service

_AIBOM_REFRESH_STOP_JOIN_TIMEOUT_SECONDS = _constants._AIBOM_REFRESH_STOP_JOIN_TIMEOUT_SECONDS
_AUDIT_REMEDIATION_ACTIONS = _constants._AUDIT_REMEDIATION_ACTIONS
_AUTH_AUDIT_COALESCE_SECONDS = _constants._AUTH_AUDIT_COALESCE_SECONDS
_AUTH_AUDIT_KEY_LIMIT = _constants._AUTH_AUDIT_KEY_LIMIT
_AUTH_AUDIT_SQLITE_TIMEOUT_SECONDS = _constants._AUTH_AUDIT_SQLITE_TIMEOUT_SECONDS
_CLOUD_APP_DASHBOARD_SESSION_ACTIONS = _constants._CLOUD_APP_DASHBOARD_SESSION_ACTIONS
_DAEMON_CONNECTION_ADMISSION_WAIT_SECONDS = _constants._DAEMON_CONNECTION_ADMISSION_WAIT_SECONDS
_DAEMON_CONTROL_ADMISSION_WAIT_SECONDS = _constants._DAEMON_CONTROL_ADMISSION_WAIT_SECONDS
_DAEMON_CONTROL_PATHS = _constants._DAEMON_CONTROL_PATHS
_DAEMON_CRITICAL_PATHS = _constants._DAEMON_CRITICAL_PATHS
_DAEMON_REQUEST_READ_TIMEOUT_SECONDS = _constants._DAEMON_REQUEST_READ_TIMEOUT_SECONDS
_DAEMON_SERVE_THREAD_START_TIMEOUT_SECONDS = _constants._DAEMON_SERVE_THREAD_START_TIMEOUT_SECONDS
_DAEMON_UNCLASSIFIED_WATCHDOG_POLL_SECONDS = _constants._DAEMON_UNCLASSIFIED_WATCHDOG_POLL_SECONDS
_DASHBOARD_CSP = _constants._DASHBOARD_CSP
_DEFAULT_HEADLESS_CLOUD_SYNC_BACKOFF_SECONDS = _constants._DEFAULT_HEADLESS_CLOUD_SYNC_BACKOFF_SECONDS
_DEFAULT_HEADLESS_CLOUD_SYNC_INTERVAL_SECONDS = _constants._DEFAULT_HEADLESS_CLOUD_SYNC_INTERVAL_SECONDS
_DEFAULT_RETRY_COPY = _constants._DEFAULT_RETRY_COPY
_DEFAULT_SUPPLY_CHAIN_REFRESH_BACKOFF_SECONDS = _constants._DEFAULT_SUPPLY_CHAIN_REFRESH_BACKOFF_SECONDS
_DEFAULT_SUPPLY_CHAIN_REFRESH_INTERVAL_SECONDS = _constants._DEFAULT_SUPPLY_CHAIN_REFRESH_INTERVAL_SECONDS
_EPHEMERAL_GUARD_DAEMON_IDLE_TIMEOUT_SECONDS = _constants._EPHEMERAL_GUARD_DAEMON_IDLE_TIMEOUT_SECONDS
_EXTENSION_CONTROL_PATHS = _constants._EXTENSION_CONTROL_PATHS
_GUARD_DAEMON_IDLE_POLL_INTERVAL_SECONDS = _constants._GUARD_DAEMON_IDLE_POLL_INTERVAL_SECONDS
_HARNESS_RETRY_COPY = _constants._HARNESS_RETRY_COPY
_HEADLESS_APP_ACTIONS = _constants._HEADLESS_APP_ACTIONS
_HEADLESS_OPERATIONS = _constants._HEADLESS_OPERATIONS
_HOSTED_GUARD_DASHBOARD_ORIGINS = _constants._HOSTED_GUARD_DASHBOARD_ORIGINS
_LOCAL_CLI_PATHS = _constants._LOCAL_CLI_PATHS
_LOCAL_DASHBOARD_SESSION_REFRESH_GRACE_SECONDS = _constants._LOCAL_DASHBOARD_SESSION_REFRESH_GRACE_SECONDS
_MAX_CONCURRENT_DAEMON_CONNECTIONS = _constants._MAX_CONCURRENT_DAEMON_CONNECTIONS
_MAX_CONCURRENT_DAEMON_CONTROL_REQUESTS = _constants._MAX_CONCURRENT_DAEMON_CONTROL_REQUESTS
_MAX_CONCURRENT_DAEMON_CRITICAL_REQUESTS = _constants._MAX_CONCURRENT_DAEMON_CRITICAL_REQUESTS
_MAX_CONCURRENT_DAEMON_REQUESTS = _constants._MAX_CONCURRENT_DAEMON_REQUESTS
_MAX_CONCURRENT_RUNTIME_HOOKS = _constants._MAX_CONCURRENT_RUNTIME_HOOKS
_MAX_CONCURRENT_RUNTIME_HOOKS_PER_HARNESS = _constants._MAX_CONCURRENT_RUNTIME_HOOKS_PER_HARNESS
_PEER_DISCONNECT_ERRORS = _constants._PEER_DISCONNECT_ERRORS
_PROTECTION_REPAIR_PROBE_COMMAND = _constants._PROTECTION_REPAIR_PROBE_COMMAND
_REMOTE_REVIEW_POST_ROUTES = _constants._REMOTE_REVIEW_POST_ROUTES
_ROOT_STATIC_FILES = _constants._ROOT_STATIC_FILES
_RUNTIME_HOOK_ADMISSION_TIMEOUT_SECONDS = _constants._RUNTIME_HOOK_ADMISSION_TIMEOUT_SECONDS
_RUNTIME_HOOK_ENV_ALLOWLIST = _constants._RUNTIME_HOOK_ENV_ALLOWLIST
_RUNTIME_HOOK_PROCESS_TIMEOUT_SECONDS = _constants._RUNTIME_HOOK_PROCESS_TIMEOUT_SECONDS
_RUNTIME_POST_HOOK_PROCESS_TIMEOUT_SECONDS = _constants._RUNTIME_POST_HOOK_PROCESS_TIMEOUT_SECONDS
_SUPPLY_CHAIN_CONNECT_POLL_AFTER_MS = _constants._SUPPLY_CHAIN_CONNECT_POLL_AFTER_MS
_SUPPLY_CHAIN_CONNECT_WAIT_TIMEOUT_SECONDS = _constants._SUPPLY_CHAIN_CONNECT_WAIT_TIMEOUT_SECONDS
_SUPPLY_CHAIN_PACKAGE_ACTIONS = _constants._SUPPLY_CHAIN_PACKAGE_ACTIONS

Any = _dependencies_base.Any
BaseHTTPRequestHandler = _dependencies_base.BaseHTTPRequestHandler
BinaryIO = _dependencies_base.BinaryIO
Callable = _dependencies_base.Callable
ClassVar = _dependencies_base.ClassVar
Mapping = _dependencies_base.Mapping
Path = _dependencies_base.Path
TypeAlias = _dependencies_base.TypeAlias
TypeGuard = _dependencies_base.TypeGuard
TypedDict = _dependencies_base.TypedDict
__version__ = _dependencies_base.__version__
_is_guard_action = _dependencies_base._is_guard_action
base64 = _dependencies_base.base64
cast = _dependencies_base.cast
datetime = _dependencies_base.datetime
errno = _dependencies_base.errno
hashlib = _dependencies_base.hashlib
hmac = _dependencies_base.hmac
inspect = _dependencies_base.inspect
json = _dependencies_base.json
logging = _dependencies_base.logging
math = _dependencies_base.math
mimetypes = _dependencies_base.mimetypes
os = _dependencies_base.os
parse_qs = _dependencies_base.parse_qs
parse_qsl = _dependencies_base.parse_qsl
platform = _dependencies_base.platform
secrets = _dependencies_base.secrets
socket = _dependencies_base.socket
sqlite3 = _dependencies_base.sqlite3
stat = _dependencies_base.stat
suppress = _dependencies_base.suppress
tempfile = _dependencies_base.tempfile
threading = _dependencies_base.threading
time = _dependencies_base.time
timezone = _dependencies_base.timezone
unquote = _dependencies_base.unquote
urlencode = _dependencies_base.urlencode
urlparse = _dependencies_base.urlparse
urlunparse = _dependencies_base.urlunparse
uuid = _dependencies_base.uuid

APPROVAL_SCOPE_CONTRACT_VERSION_PREFIX = _dependencies_guard.APPROVAL_SCOPE_CONTRACT_VERSION_PREFIX
ApprovalAttentionCoordinator = _dependencies_guard.ApprovalAttentionCoordinator
ApprovalGateError = _dependencies_guard.ApprovalGateError
ApprovalRequestAlreadyResolvedError = _dependencies_guard.ApprovalRequestAlreadyResolvedError
ApprovalRequestNotFoundError = _dependencies_guard.ApprovalRequestNotFoundError
CONNECT_SYNC_AUTH_CONTEXT_KEY = _dependencies_guard.CONNECT_SYNC_AUTH_CONTEXT_KEY
CloudExceptionRequestError = _dependencies_guard.CloudExceptionRequestError
CloudReviewSyncWorker = _dependencies_guard.CloudReviewSyncWorker
DECISION_SCOPE_VALUES = _dependencies_guard.DECISION_SCOPE_VALUES
DEFAULT_LOCAL_DASHBOARD_SESSION_TTL_SECONDS = _dependencies_guard.DEFAULT_LOCAL_DASHBOARD_SESSION_TTL_SECONDS
DecisionScope = _dependencies_guard.DecisionScope
GuardConfig = _dependencies_guard.GuardConfig
HarnessContext = _dependencies_guard.HarnessContext
IneligibleApprovalScopeError = _dependencies_guard.IneligibleApprovalScopeError
LOCAL_DASHBOARD_SESSION_AUDIENCE = _dependencies_guard.LOCAL_DASHBOARD_SESSION_AUDIENCE
LOCAL_DASHBOARD_SESSION_STARTED_AT_CLAIM = _dependencies_guard.LOCAL_DASHBOARD_SESSION_STARTED_AT_CLAIM
MANAGED_POLICY_BUNDLE_KEYRING_PROVENANCE_STATE_KEY = (
    _dependencies_guard.MANAGED_POLICY_BUNDLE_KEYRING_PROVENANCE_STATE_KEY
)
MAX_LOCAL_DASHBOARD_SESSION_AGE_SECONDS = _dependencies_guard.MAX_LOCAL_DASHBOARD_SESSION_AGE_SECONDS
POLICY_BUNDLE_V2_CONTRACT = _dependencies_guard.POLICY_BUNDLE_V2_CONTRACT
PackageFirewallActionRateLimiter = _dependencies_guard.PackageFirewallActionRateLimiter
ParsedManagedControlsPolicy = _dependencies_guard.ParsedManagedControlsPolicy
PolicyDecision = _dependencies_guard.PolicyDecision
StaleApprovalScopeContractError = _dependencies_guard.StaleApprovalScopeContractError
VALID_RECEIPT_REDACTION_LEVELS = _dependencies_guard.VALID_RECEIPT_REDACTION_LEVELS
_AIBOM_AUTO_SYNC_INTERVAL_SECONDS = _dependencies_guard._AIBOM_AUTO_SYNC_INTERVAL_SECONDS
_build_sync_auth_context = _dependencies_guard._build_sync_auth_context
_native_mode_requires_rust = _dependencies_guard._native_mode_requires_rust
_persist_oauth_local_credentials = _dependencies_guard._persist_oauth_local_credentials
activate_with_reason = _dependencies_guard.activate_with_reason
apply_approval_resolution = _dependencies_guard.apply_approval_resolution
apply_guard_connect_sync_result = _dependencies_guard.apply_guard_connect_sync_result
apply_managed_install = _dependencies_guard.apply_managed_install
approval_gate_input_from_mapping = _dependencies_guard.approval_gate_input_from_mapping
approval_gate_public_config = _dependencies_guard.approval_gate_public_config
begin_totp_enrollment = _dependencies_guard.begin_totp_enrollment
build_approval_browser_url = _dependencies_guard.build_approval_browser_url
build_guard_update_status_payload = _dependencies_guard.build_guard_update_status_payload
build_harness_setup_plan = _dependencies_guard.build_harness_setup_plan
build_harness_verification = _dependencies_guard.build_harness_verification
build_local_dashboard_session_token = _dependencies_guard.build_local_dashboard_session_token
build_receipt = _dependencies_guard.build_receipt
build_runtime_snapshot = _dependencies_guard.build_runtime_snapshot
build_workspace_audit_payload = _dependencies_guard.build_workspace_audit_payload
bulk_allow_read_only_once = _dependencies_guard.bulk_allow_read_only_once
complete_codex_live_decision = _dependencies_guard.complete_codex_live_decision
confirm_totp_enrollment = _dependencies_guard.confirm_totp_enrollment
desktop_notification_setup_payload = _dependencies_guard.desktop_notification_setup_payload
disable_totp = _dependencies_guard.disable_totp
editable_guard_settings = _dependencies_guard.editable_guard_settings
ensure_desktop_notification_setup = _dependencies_guard.ensure_desktop_notification_setup
escape_json_for_html = _dependencies_guard.escape_json_for_html
exchange_guard_authorization_code = _dependencies_guard.exchange_guard_authorization_code
failed_browser_connect_flow_state = _dependencies_guard.failed_browser_connect_flow_state
fetch_cloud_exception_requests = _dependencies_guard.fetch_cloud_exception_requests
format_local_http_origin = _dependencies_guard.format_local_http_origin
get_adapter = _dependencies_guard.get_adapter
get_request_resume_status = _dependencies_guard.get_request_resume_status
headless_sync_retry_summary = _dependencies_guard.headless_sync_retry_summary
list_harness_setup_items = _dependencies_guard.list_harness_setup_items
load_guard_config = _dependencies_guard.load_guard_config
macos_notification_guidance = _dependencies_guard.macos_notification_guidance
managed_install_audit_workspace_dirs = _dependencies_guard.managed_install_audit_workspace_dirs
open_browser_url = _dependencies_guard.open_browser_url
package_firewall_action_states = _dependencies_guard.package_firewall_action_states
package_firewall_available_actions = _dependencies_guard.package_firewall_available_actions
package_firewall_block_details = _dependencies_guard.package_firewall_block_details
package_firewall_operation_allowed = _dependencies_guard.package_firewall_operation_allowed
package_firewall_receipt_metadata = _dependencies_guard.package_firewall_receipt_metadata
policy_bundle_acknowledgement_payload = _dependencies_guard.policy_bundle_acknowledgement_payload
policy_bundle_is_enforceable = _dependencies_guard.policy_bundle_is_enforceable
policy_bundle_keyring_payload = _dependencies_guard.policy_bundle_keyring_payload
policy_bundle_rejection_message = _dependencies_guard.policy_bundle_rejection_message
protection_is_off = _dependencies_guard.protection_is_off
publish_insights_share = _dependencies_guard.publish_insights_share
python_oracle_surface_enabled = _dependencies_guard.python_oracle_surface_enabled
reconcile_connect_state_with_oauth_entitlement = _dependencies_guard.reconcile_connect_state_with_oauth_entitlement
record_package_shim_audit_result = _dependencies_guard.record_package_shim_audit_result
request_scope_contract_payload = _dependencies_guard.request_scope_contract_payload
require_harness_disconnect_gate = _dependencies_guard.require_harness_disconnect_gate
require_high_risk = _dependencies_guard.require_high_risk
reset_guard_settings = _dependencies_guard.reset_guard_settings
resolve_codex_live_allow_authority = _dependencies_guard.resolve_codex_live_allow_authority
resolve_connect_url = _dependencies_guard.resolve_connect_url
resolve_guard_oauth_client_config = _dependencies_guard.resolve_guard_oauth_client_config
resolve_package_firewall_entitlement = _dependencies_guard.resolve_package_firewall_entitlement
resolve_package_firewall_entitlement_with_refresh = (
    _dependencies_guard.resolve_package_firewall_entitlement_with_refresh
)
resolve_request_scope_selection = _dependencies_guard.resolve_request_scope_selection
resolve_supply_chain_audit_workspace_dir = _dependencies_guard.resolve_supply_chain_audit_workspace_dir
retry_request_resume = _dependencies_guard.retry_request_resume
revalidate_codex_live_allow = _dependencies_guard.revalidate_codex_live_allow
revoke_approval_gate_cooldown = _dependencies_guard.revoke_approval_gate_cooldown
start_cloud_sync_sync_worker = _dependencies_guard.start_cloud_sync_sync_worker
start_guard_browser_session = _dependencies_guard.start_guard_browser_session
stop_cloud_sync_sync_worker = _dependencies_guard.stop_cloud_sync_sync_worker
submit_cloud_exception_request = _dependencies_guard.submit_cloud_exception_request
sync_aibom_snapshots_if_due = _dependencies_guard.sync_aibom_snapshots_if_due
sync_supply_chain_cloud_state = _dependencies_guard.sync_supply_chain_cloud_state
uninstall_confirmation_token = _dependencies_guard.uninstall_confirmation_token
update_approval_gate_settings = _dependencies_guard.update_approval_gate_settings
update_guard_settings = _dependencies_guard.update_guard_settings
update_guard_update_channel = _dependencies_guard.update_guard_update_channel
validate_approval_gate_settings = _dependencies_guard.validate_approval_gate_settings
validate_synced_policy_bundle = _dependencies_guard.validate_synced_policy_bundle

ActivityApprovalReuseStatus = _dependencies_runtime.ActivityApprovalReuseStatus
ActivityDecisionReason = _dependencies_runtime.ActivityDecisionReason
BUILT_IN_COMMAND_EXTENSION_REGISTRY = _dependencies_runtime.BUILT_IN_COMMAND_EXTENSION_REGISTRY
BoundedThreadingHTTPServer = _dependencies_runtime.BoundedThreadingHTTPServer
CommandActivityDecisionFacts = _dependencies_runtime.CommandActivityDecisionFacts
CommandShadowCohort = _dependencies_runtime.CommandShadowCohort
CommandShadowControl = _dependencies_runtime.CommandShadowControl
DEFAULT_GUARD_EVENT_LIMIT = _dependencies_runtime.DEFAULT_GUARD_EVENT_LIMIT
DEFAULT_RECEIPT_DETAIL_LIMIT = _dependencies_runtime.DEFAULT_RECEIPT_DETAIL_LIMIT
ExtensionControlAuthorityError = _dependencies_runtime.ExtensionControlAuthorityError
ExtensionControlAuthorityView = _dependencies_runtime.ExtensionControlAuthorityView
ExtensionControlRuntime = _dependencies_runtime.ExtensionControlRuntime
ExtensionControlRuntimeSnapshot = _dependencies_runtime.ExtensionControlRuntimeSnapshot
GuardStore = _dependencies_runtime.GuardStore
GuardSurfaceRuntime = _dependencies_runtime.GuardSurfaceRuntime
GuardSyncAuthorizationExpiredError = _dependencies_runtime.GuardSyncAuthorizationExpiredError
GuardSyncNotAvailableError = _dependencies_runtime.GuardSyncNotAvailableError
GuardSyncNotConfiguredError = _dependencies_runtime.GuardSyncNotConfiguredError
InvalidApprovalCursorError = _dependencies_runtime.InvalidApprovalCursorError
NetworkSupervisor = _dependencies_runtime.NetworkSupervisor
_build_policy_bundle_decisions = _dependencies_runtime._build_policy_bundle_decisions
_daemon_version_supported = _dependencies_runtime._daemon_version_supported
_guard_device_metadata = _dependencies_runtime._guard_device_metadata
_persist_cloud_receipt_redaction_level = _dependencies_runtime._persist_cloud_receipt_redaction_level
_policy_bundle_acceptance_checkpoint = _dependencies_runtime._policy_bundle_acceptance_checkpoint
_policy_bundle_cloud_exception_items = _dependencies_runtime._policy_bundle_cloud_exception_items
_policy_bundle_downgrade_reference = _dependencies_runtime._policy_bundle_downgrade_reference
_policy_bundle_is_version_downgrade = _dependencies_runtime._policy_bundle_is_version_downgrade
_requeue_cloud_review_privacy_projection = _dependencies_runtime._requeue_cloud_review_privacy_projection
_reset_cloud_receipt_redaction_authority = _dependencies_runtime._reset_cloud_receipt_redaction_authority
_resolve_guard_sync_auth_context = _dependencies_runtime._resolve_guard_sync_auth_context
_validate_cached_policy_bundle = _dependencies_runtime._validate_cached_policy_bundle
activate_package_shims = _dependencies_runtime.activate_package_shims
baseline_command_shadow_proposal = _dependencies_runtime.baseline_command_shadow_proposal
build_command_shadow_observation = _dependencies_runtime.build_command_shadow_observation
build_network_status = _dependencies_runtime.build_network_status
build_pre_hook_evidence = _dependencies_runtime.build_pre_hook_evidence
clear_evidence = _dependencies_runtime.clear_evidence
coordinate_supply_chain_repair = _dependencies_runtime.coordinate_supply_chain_repair
count_evidence = _dependencies_runtime.count_evidence
evaluate_command = _dependencies_runtime.evaluate_command
evidence_record_to_dict = _dependencies_runtime.evidence_record_to_dict
export_evidence_csv = _dependencies_runtime.export_evidence_csv
export_evidence_json = _dependencies_runtime.export_evidence_json
handle_command_activity_analytics = _dependencies_runtime.handle_command_activity_analytics
handle_command_activity_diagnostics = _dependencies_runtime.handle_command_activity_diagnostics
handle_command_activity_feedback = _dependencies_runtime.handle_command_activity_feedback
handle_command_activity_list = _dependencies_runtime.handle_command_activity_list
handle_command_extensions = _dependencies_runtime.handle_command_extensions
list_evidence = _dependencies_runtime.list_evidence
load_managed_provider_registry = _dependencies_runtime.load_managed_provider_registry
package_shim_dashboard_status = _dependencies_runtime.package_shim_dashboard_status
package_shim_status = _dependencies_runtime.package_shim_status
package_shim_supported_managers = _dependencies_runtime.package_shim_supported_managers
parse_command_activity_event_cursor = _dependencies_runtime.parse_command_activity_event_cursor
prepare_guard_cloud_connect_authorization = _dependencies_runtime.prepare_guard_cloud_connect_authorization
probe_package_shim_intercepts = _dependencies_runtime.probe_package_shim_intercepts
project_network_supervisor_health = _dependencies_runtime.project_network_supervisor_health
reconcile_runtime_artifacts = _dependencies_runtime.reconcile_runtime_artifacts
repair_failing_managed_harness_hooks = _dependencies_runtime.repair_failing_managed_harness_hooks
repair_guard_cloud_connect_storage = _dependencies_runtime.repair_guard_cloud_connect_storage
repair_sync_intelligence = _dependencies_runtime.repair_sync_intelligence
sqlite_connect_timeout_override = _dependencies_runtime.sqlite_connect_timeout_override
stable_digest_hex = _dependencies_runtime.stable_digest_hex
stream_command_activity_events = _dependencies_runtime.stream_command_activity_events
sync_local_guard_cloud_proof = _dependencies_runtime.sync_local_guard_cloud_proof
sync_supply_chain_bundle = _dependencies_runtime.sync_supply_chain_bundle
trusted_temporary_root_for_path = _dependencies_runtime.trusted_temporary_root_for_path
uninstall_package_shims = _dependencies_runtime.uninstall_package_shims

CHALLENGE_HOOK_PATHS = _dependencies_services.CHALLENGE_HOOK_PATHS
CommandQueueWorker = _dependencies_services.CommandQueueWorker
DAEMON_DISCOVERY_CHALLENGE_TTL_SECONDS = _dependencies_services.DAEMON_DISCOVERY_CHALLENGE_TTL_SECONDS
DAEMON_DISCOVERY_PROTOCOL_VERSION = _dependencies_services.DAEMON_DISCOVERY_PROTOCOL_VERSION
DASHBOARD_RECONNECT_PROTOCOL_VERSION = _dependencies_services.DASHBOARD_RECONNECT_PROTOCOL_VERSION
DaemonDiagnostics = _dependencies_services.DaemonDiagnostics
ExtensionControlApiError = _dependencies_services.ExtensionControlApiError
ExtensionControlApiService = _dependencies_services.ExtensionControlApiService
GUARD_DAEMON_COMPATIBILITY_VERSION = _dependencies_services.GUARD_DAEMON_COMPATIBILITY_VERSION
HookProcessRunner = _dependencies_services.HookProcessRunner
LocalCliApiService = _dependencies_services.LocalCliApiService
RuntimeHeartbeatWriter = _dependencies_services.RuntimeHeartbeatWriter
RuntimeHookAdmissionReason = _dependencies_services.RuntimeHookAdmissionReason
RuntimeHookDeadline = _dependencies_services.RuntimeHookDeadline
RuntimeHookEvidenceWriter = _dependencies_services.RuntimeHookEvidenceWriter
RuntimeHookLane = _dependencies_services.RuntimeHookLane
RuntimeHookScheduler = _dependencies_services.RuntimeHookScheduler
_BoundedRequestExecutor = _dependencies_services._BoundedRequestExecutor
apply_local_approval_continuation = _dependencies_services.apply_local_approval_continuation
authenticated_challenge_payload = _dependencies_services.authenticated_challenge_payload
begin_service = _dependencies_services.begin_service
challenge_auth = _dependencies_services.challenge_auth
clear_guard_daemon_state_if_current = _dependencies_services.clear_guard_daemon_state_if_current
confirmed_containment_repair_signals = _dependencies_services.confirmed_containment_repair_signals
consume_dashboard_reconnect_challenge = _dependencies_services.consume_dashboard_reconnect_challenge
contain_failed_service_start = _dependencies_services.contain_failed_service_start
current_guard_daemon_runtime_fingerprint = _dependencies_services.current_guard_daemon_runtime_fingerprint
daemon_managed_controls_candidate = _dependencies_services.daemon_managed_controls_candidate
dashboard_reconnect_challenge_identity = _dependencies_services.dashboard_reconnect_challenge_identity
enable_full_capacity_for_generation = _dependencies_services.enable_full_capacity_for_generation
handle_local_cli_list = _dependencies_services.handle_local_cli_list
handle_local_cli_post = _dependencies_services.handle_local_cli_post
incomplete_protection_repair_payload = _dependencies_services.incomplete_protection_repair_payload
issue_dashboard_reconnect_challenge = _dependencies_services.issue_dashboard_reconnect_challenge
load_authenticated_daemon_state = _dependencies_services.load_authenticated_daemon_state
load_daemon_discovery_key = _dependencies_services.load_daemon_discovery_key
load_guard_daemon_auth_token = _dependencies_services.load_guard_daemon_auth_token
managed_policy_rows = _dependencies_services.managed_policy_rows
maybe_queue_first_cloud_sync = _dependencies_services.maybe_queue_first_cloud_sync
merge_dashboard_update_progress = _dependencies_services.merge_dashboard_update_progress
prepare_dashboard_reconnect_authorization = _dependencies_services.prepare_dashboard_reconnect_authorization
prepare_native_hook_policy = _dependencies_services.prepare_native_hook_policy
queue_sync_with_optional_publish = _dependencies_services.queue_sync_with_optional_publish
record_daemon_lifecycle_event = _dependencies_services.record_daemon_lifecycle_event
refresh_command_queue_worker = _dependencies_services.refresh_command_queue_worker
release_guard_daemon_owner_lock = _dependencies_services.release_guard_daemon_owner_lock
repair_approval_center_locator = _dependencies_services.repair_approval_center_locator
request_auth = _dependencies_services.request_auth
schedule_guard_dashboard_update = _dependencies_services.schedule_guard_dashboard_update
start_command_queue_worker = _dependencies_services.start_command_queue_worker
start_serve_thread = _dependencies_services.start_serve_thread
startup_generation_is_current = _dependencies_services.startup_generation_is_current
stop_command_queue_worker = _dependencies_services.stop_command_queue_worker
write_guard_daemon_state = _dependencies_services.write_guard_daemon_state

_GuardDaemonHandler = _handler._GuardDaemonHandler

_managed_controls_publish_for = _helpers_cloud_sync._managed_controls_publish_for
_maybe_queue_first_cloud_sync = _helpers_cloud_sync._maybe_queue_first_cloud_sync
_queue_headless_cloud_sync = _helpers_cloud_sync._queue_headless_cloud_sync
_queue_headless_cloud_sync_with_optional_publish = _helpers_cloud_sync._queue_headless_cloud_sync_with_optional_publish
_run_headless_cloud_sync = _helpers_cloud_sync._run_headless_cloud_sync
_run_headless_cloud_sync_with_optional_publish = _helpers_cloud_sync._run_headless_cloud_sync_with_optional_publish

_begin_guard_cloud_connect_state = _helpers_guard_connect._begin_guard_cloud_connect_state
_complete_browser_oauth_connect = _helpers_guard_connect._complete_browser_oauth_connect
_copy_guard_cloud_connect_state = _helpers_guard_connect._copy_guard_cloud_connect_state
_default_guard_cloud_connect_flow = _helpers_guard_connect._default_guard_cloud_connect_flow
_finalize_daemon_guard_connect_payload = _helpers_guard_connect._finalize_daemon_guard_connect_payload
_guard_cloud_connect_repair_mode = _helpers_guard_connect._guard_cloud_connect_repair_mode
_guard_cloud_connect_repair_mode_from_health = _helpers_guard_connect._guard_cloud_connect_repair_mode_from_health
_guard_cloud_connect_required_for_insights = _helpers_guard_connect._guard_cloud_connect_required_for_insights
_guard_cloud_connect_succeeded = _helpers_guard_connect._guard_cloud_connect_succeeded
_resolve_guard_cloud_connect_flow = _helpers_guard_connect._resolve_guard_cloud_connect_flow
_set_guard_cloud_connect_state = _helpers_guard_connect._set_guard_cloud_connect_state
_sync_local_guard_cloud_proof_with_optional_auth_context = (
    _helpers_guard_connect._sync_local_guard_cloud_proof_with_optional_auth_context
)
_sync_supply_chain_cloud_state_with_optional_auth_context = (
    _helpers_guard_connect._sync_supply_chain_cloud_state_with_optional_auth_context
)

_cloud_app_dashboard_session_actions = _helpers_headless._cloud_app_dashboard_session_actions
_headless_action_error_payload = _helpers_headless._headless_action_error_payload
_headless_action_state_payload = _helpers_headless._headless_action_state_payload
_headless_app_status_from_result = _helpers_headless._headless_app_status_from_result
_headless_detection_status_to_app_status = _helpers_headless._headless_detection_status_to_app_status
_headless_error_payload = _helpers_headless._headless_error_payload
_headless_safe_failure_reasons = _helpers_headless._headless_safe_failure_reasons
_supply_chain_package_action_error_response = _helpers_headless._supply_chain_package_action_error_response

_activate_package_firewall_runtime = _helpers_package_connect._activate_package_firewall_runtime
_begin_package_firewall_connect_state = _helpers_package_connect._begin_package_firewall_connect_state
_copy_package_firewall_connect_state = _helpers_package_connect._copy_package_firewall_connect_state
_default_package_firewall_connect_flow = _helpers_package_connect._default_package_firewall_connect_flow
_guard_cloud_connect_state_is_in_flight = _helpers_package_connect._guard_cloud_connect_state_is_in_flight
_package_firewall_connect_action_label = _helpers_package_connect._package_firewall_connect_action_label
_package_firewall_connect_needs_repair = _helpers_package_connect._package_firewall_connect_needs_repair
_package_firewall_connect_url = _helpers_package_connect._package_firewall_connect_url
_repair_detected_package_shims = _helpers_package_connect._repair_detected_package_shims
_resolve_package_firewall_connect_flow = _helpers_package_connect._resolve_package_firewall_connect_flow
_set_package_firewall_connect_state = _helpers_package_connect._set_package_firewall_connect_state

_approval_center_browser_url = _helpers_support._approval_center_browser_url
_build_local_url = _helpers_support._build_local_url
_build_resolution_copy = _helpers_support._build_resolution_copy
_dashboard_session_signature = _helpers_support._dashboard_session_signature
_decode_dashboard_session_payload = _helpers_support._decode_dashboard_session_payload
_guard_daemon_idle_timeout_seconds = _helpers_support._guard_daemon_idle_timeout_seconds
_guard_home_is_ephemeral = _helpers_support._guard_home_is_ephemeral
_int_query_value = _helpers_support._int_query_value
_normalized_iso_timestamp_string = _helpers_support._normalized_iso_timestamp_string
_now = _helpers_support._now
_parse_iso_timestamp = _helpers_support._parse_iso_timestamp
_repair_command_activity_persistence_health = _helpers_support._repair_command_activity_persistence_health
_settings_export_payload = _helpers_support._settings_export_payload
_settings_response_payload = _helpers_support._settings_response_payload
_validate_dashboard_bundle = _helpers_support._validate_dashboard_bundle

_build_snapshot_payload = _helpers_values._build_snapshot_payload
_codex_live_replay_authority = _helpers_values._codex_live_replay_authority
_headless_cloud_sync_store_key = _helpers_values._headless_cloud_sync_store_key
_is_decision_scope = _helpers_values._is_decision_scope
_is_string_object_dict = _helpers_values._is_string_object_dict
_runtime_hook_env_overlay_from_payload = _helpers_values._runtime_hook_env_overlay_from_payload
_runtime_hook_remaining_hint = _helpers_values._runtime_hook_remaining_hint
_safe_int = _helpers_values._safe_int

_GuardDaemonHTTPServer = _http._GuardDaemonHTTPServer

GuardDaemonServer = _service.GuardDaemonServer

_LOGGER = logging.getLogger(__name__)

_HEADLESS_CLOUD_SYNC_STATE_LOCK = threading.Lock()

_HEADLESS_CLOUD_SYNC_IN_FLIGHT: set[str] = set()


class _HookPathValidationError(ValueError):
    def __init__(self, parameter: str, reason: str) -> None:
        self.parameter = parameter
        self.reason = reason
        parameter_slug = parameter.replace("-", "_")
        super().__init__(f"invalid_hook_{parameter_slug}_path")
        self.code = f"invalid_hook_{parameter_slug}_path"


class _CursorReceiptContext(TypedDict):
    action_scope: str
    artifact_name: str
    capabilities_summary: str
    changed_capability: str
    scanner_evidence: dict[str, object]
    source_scope: str
    summary: dict[str, object]


_AuthAuditKey: TypeAlias = tuple[str, str, str | None, str | None, bool, bool, bool]


class _AuthAuditWindow(TypedDict):
    started_at: float
    suppressed_count: int
    pending: bool
    persisted: bool


_STATIC_DIR = Path(__file__).with_name("static")

_INDEX_PATH = _STATIC_DIR / "index.html"

_ENTRY_PATH = _STATIC_DIR / "assets" / "guard-dashboard.js"

_GuardDaemonHttpServer = _GuardDaemonHTTPServer
