"""Declared event capabilities for supported harnesses."""

from .contract_capability_values import _capability
from .contract_models import HarnessEventCapability

AGENT_EVENT_CAPABILITIES: dict[str, tuple[HarnessEventCapability, ...]] = {
    "grok": (
        _capability(
            "grok",
            "PreToolUse",
            "native_hook",
            "blocking",
            ("observe", "block", "approval"),
            "The catch-all pre-tool hook returns a native deny when Guard blocks the tool call.",
            "Grok must invoke the managed PreToolUse hook and honor its decision for tool and subagent calls.",
            ("Post-tool events do not prevent an action that already executed.",),
            "src/codex_plugin_scanner/guard/adapters/grok_hooks.py:grok_hook_response_from_guard",
        ),
        _capability(
            "grok",
            "UserPromptSubmit",
            "native_hook",
            "blocking",
            ("observe", "block"),
            "Guard returns decision:block for protected prompts and unavailable prompt review.",
            "Grok must honor UserPromptSubmit decision:block before delivering a user-typed prompt.",
            ("Auto-wake and subagent prompts are passive; Grok fails open if the hook process crashes or times out.",),
            "src/codex_plugin_scanner/guard/daemon/hook_worker_responses.py:harness_json_from_native_prompt",
        ),
        _capability(
            "grok",
            "PostToolUse",
            "native_hook",
            "observe",
            ("observe",),
            "The native post-tool hook records an event after execution and cannot replace its result.",
            "Grok must invoke the managed PostToolUse hook after the tool event.",
            ("Post-tool observation does not block or replace model-visible output.",),
            "src/codex_plugin_scanner/guard/adapters/grok_hooks.py:_OBSERVE_ONLY_EVENTS",
        ),
    ),
    "pi": (
        _capability(
            "pi",
            "UserPromptSubmit",
            "managed_extension",
            "screening",
            ("observe", "block", "approval"),
            "Extension or Guard runtime failure returns a bounded fail-closed prompt decision.",
            "Pi must load the current managed Guard extension and forward input events to the Guard runtime.",
            ("Package installation and update flows happen outside the runtime extension bridge.",),
            'src/codex_plugin_scanner/guard/adapters/pi_extension_source.py:pi.on("input")',
        ),
        _capability(
            "pi",
            "PreToolUse",
            "managed_extension",
            "blocking",
            ("observe", "block", "approval"),
            "Extension or Guard runtime failure returns a bounded fail-closed tool decision.",
            "Pi must load the current managed Guard extension and forward tool_call events to Guard before execution.",
            ("A present extension file alone does not prove Pi loaded it or suppressed a live tool call.",),
            'src/codex_plugin_scanner/guard/adapters/pi_extension_source.py:pi.on("tool_call")',
        ),
        _capability(
            "pi",
            "PostToolUse",
            "managed_extension",
            "replace_or_withhold",
            ("observe", "block", "rewrite"),
            "Unavailable or failed review withholds the tool result; reviewed content may replace it.",
            "Pi must load the current managed Guard extension and forward tool_result events before model delivery.",
            ("A synthetic extension canary does not prove live Pi model-visible replacement.",),
            'src/codex_plugin_scanner/guard/adapters/pi_extension_source.py:pi.on("tool_result")',
        ),
    ),
    "omp": (
        _capability(
            "omp",
            "UserPromptSubmit",
            "managed_extension",
            "screening",
            ("observe", "block", "approval"),
            "Extension or Guard runtime failure returns a bounded fail-closed prompt decision.",
            "Oh My Pi must load the managed Guard extension and forward input events to Guard.",
            ("Package installation and update flows happen outside the runtime extension bridge.",),
            'src/codex_plugin_scanner/guard/adapters/pi_extension_source.py:pi.on("input")',
        ),
        _capability(
            "omp",
            "PreToolUse",
            "managed_extension",
            "blocking",
            ("observe", "block", "approval"),
            "Extension or Guard runtime failure returns a bounded fail-closed tool decision.",
            "Oh My Pi must load the managed Guard extension and forward tool_call events before execution.",
            ("A present extension file alone does not prove live tool suppression.",),
            'src/codex_plugin_scanner/guard/adapters/pi_extension_source.py:pi.on("tool_call")',
        ),
        _capability(
            "omp",
            "PostToolUse",
            "managed_extension",
            "replace_or_withhold",
            ("observe", "block", "rewrite"),
            "Unavailable or failed review withholds the tool result; reviewed content may replace it.",
            "Oh My Pi must load the managed Guard extension and forward tool_result events before model delivery.",
            ("A synthetic extension canary does not prove live model-visible replacement.",),
            'src/codex_plugin_scanner/guard/adapters/pi_extension_source.py:pi.on("tool_result")',
        ),
    ),
    "devin": (
        _capability(
            "devin",
            "PreToolUse",
            "native_hook",
            "blocking",
            ("observe", "block", "approval"),
            "Malformed payload, hook failure, or unavailable Guard authority fails closed before tool execution.",
            "Devin must invoke the managed PreToolUse hook and honor its block decision before running the tool.",
            ("A source declaration does not prove that a live Devin session honored a deny response.",),
            "src/codex_plugin_scanner/guard/adapters/devin.py:_sync_managed_hook_groups",
        ),
        _capability(
            "devin",
            "PermissionRequest",
            "native_hook",
            "approval",
            ("observe", "block", "approval"),
            "Approval hook failures fail closed and leave the request pending or denied.",
            "Devin must preserve the managed PermissionRequest hook group in its user config.",
            ("Native approval UX and Guard evidence still require a live host/version check.",),
            "src/codex_plugin_scanner/guard/adapters/devin.py:_sync_managed_hook_groups",
        ),
        _capability(
            "devin",
            "UserPromptSubmit",
            "native_hook",
            "screening",
            ("observe", "block", "approval"),
            "Prompt hook failures return a bounded fail-closed response where Devin honors the hook contract.",
            "Devin must expose UserPromptSubmit and preserve the Guard hook response schema.",
            ("Prompt screening does not prove downstream model or host request rewriting.",),
            "src/codex_plugin_scanner/guard/adapters/devin.py:_sync_managed_hook_groups",
        ),
        _capability(
            "devin",
            "PostToolUse",
            "native_hook",
            "observe",
            ("observe",),
            (
                "Post-tool transport failures are surfaced as unavailable review; a completed host action "
                "cannot be undone."
            ),
            "Devin must invoke the managed PostToolUse hook after the tool event.",
            ("Post-tool observation does not block or replace model-visible output.",),
            "src/codex_plugin_scanner/guard/adapters/devin.py:_sync_managed_hook_groups",
        ),
    ),
}
