"""Generated Pi managed extension source."""

from __future__ import annotations

import json
from pathlib import Path

GUARD_HOOK_TIMEOUT_MS = 10_000
GUARD_HOOK_TEXT_LIMIT_CHARS = 12_000
GUARD_HOOK_CONTENT_ITEM_LIMIT = 24
GUARD_HOOK_OBJECT_KEY_LIMIT = 24
GUARD_HOOK_MAX_DEPTH = 24
GUARD_HOOK_MAX_SERIALIZED_PAYLOAD_CHARS = 24_000


def managed_extension_source(*, guard_home: Path, home_dir: Path, settings_path: Path) -> str:
    guard_args = ["hook", "--guard-home", str(guard_home), "--harness", "pi"]
    if home_dir.resolve() != Path.home().resolve():
        guard_args.extend(["--home", str(home_dir)])
    guard_args_json = json.dumps(guard_args)
    guard_home_json = json.dumps(str(guard_home))
    home_dir_json = json.dumps(str(home_dir))
    home_dir_is_default_json = "true" if home_dir.resolve() == Path.home().resolve() else "false"
    config_path_json = json.dumps(str(settings_path))
    return (
        'import { spawnSync } from "node:child_process";\n'
        'import { createCipheriv, createHash, randomBytes } from "node:crypto";\n'
        'import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";\n'
        'import { tmpdir } from "node:os";\n'
        'import { join } from "node:path";\n'
        'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n'
        "\n"
        'const GUARD_COMMAND_CANDIDATES = ["plugin-guard", "hol-guard"] as const;\n'
        f"const GUARD_ARGS = {guard_args_json};\n"
        f"const GUARD_HOME = {guard_home_json};\n"
        f"const GUARD_HOME_DIR = {home_dir_json};\n"
        f"const GUARD_HOME_DIR_IS_DEFAULT = {home_dir_is_default_json};\n"
        f"const GUARD_CONFIG_PATH = {config_path_json};\n"
        f"const GUARD_TIMEOUT_MS = {GUARD_HOOK_TIMEOUT_MS};\n"
        f"const GUARD_TEXT_LIMIT_CHARS = {GUARD_HOOK_TEXT_LIMIT_CHARS};\n"
        f"const GUARD_CONTENT_ITEM_LIMIT = {GUARD_HOOK_CONTENT_ITEM_LIMIT};\n"
        f"const GUARD_OBJECT_KEY_LIMIT = {GUARD_HOOK_OBJECT_KEY_LIMIT};\n"
        f"const GUARD_MAX_DEPTH = {GUARD_HOOK_MAX_DEPTH};\n"
        f"const GUARD_MAX_SERIALIZED_PAYLOAD_CHARS = {GUARD_HOOK_MAX_SERIALIZED_PAYLOAD_CHARS};\n"
        "const GUARD_SOURCE_REF_MAX_OUTPUT_CHARS = 5 * 1024 * 1024;\n"
        "const GUARD_SOURCE_REF_ALLOWED_TOOL_NAMES = new Set([\n"
        '  "read", "read_file", "open_file", "view", "view_file", "cat_file", "Read", "View"\n'
        "]);\n"
        "\n"
        "type GuardResponse = {\n"
        "  decision?: string;\n"
        "  reason?: string;\n"
        '  model_output_action?: "allow_original" | "replace_with_reviewed_excerpt" | "block" | "not_applicable";\n'
        "  reviewed_output_sha256?: string;\n"
        '  notice?: "none" | "excerpt" | "warning";\n'
        "  reason_code?: string;\n"
        "};\n"
        "type OutputDigest = {\n"
        "  sha256: string | null;\n"
        "  chars: number;\n"
        "  textForExcerpt: string;\n"
        "  excerptTruncated: boolean;\n"
        "  traversalTruncated: boolean;\n"
        "};\n"
        "\n"
        "function digestOutputText(value: unknown): OutputDigest {\n"
        "  const hash = createHash('sha256');\n"
        "  let chars = 0;\n"
        "  let textForExcerpt = '';\n"
        "  let excerptTruncated = false;\n"
        "  let traversalTruncated = false;\n"
        "  const seen = new WeakSet<object>();\n"
        "  function update(text: string): void {\n"
        "    hash.update(text, 'utf8');\n"
        "    chars += text.length;\n"
        "    if (textForExcerpt.length < GUARD_TEXT_LIMIT_CHARS) {\n"
        "      const remaining = GUARD_TEXT_LIMIT_CHARS - textForExcerpt.length;\n"
        "      if (text.length <= remaining) {\n"
        "        textForExcerpt += text;\n"
        "      } else {\n"
        "        textForExcerpt += text.slice(0, remaining);\n"
        "        excerptTruncated = true;\n"
        "      }\n"
        "    }\n"
        "    if (chars > GUARD_SOURCE_REF_MAX_OUTPUT_CHARS) {\n"
        "      traversalTruncated = true;\n"
        "    }\n"
        "  }\n"
        "  function traverse(val: unknown, depth: number): void {\n"
        "    if (traversalTruncated) return;\n"
        "    if (typeof val === 'string') { update(val); return; }\n"
        "    if (val === undefined || val === null) return;\n"
        "    if (typeof val === 'number' || typeof val === 'boolean') return;\n"
        "    if (typeof val === 'bigint') { update(val.toString()); return; }\n"
        "    if (typeof val !== 'object') { traversalTruncated = true; return; }\n"
        "    const obj = val as object;\n"
        "    if (seen.has(obj)) { traversalTruncated = true; return; }\n"
        "    if (depth > GUARD_MAX_DEPTH) { traversalTruncated = true; return; }\n"
        "    seen.add(obj);\n"
        "    if (Array.isArray(val)) {\n"
        "      if (val.length > GUARD_CONTENT_ITEM_LIMIT) { traversalTruncated = true; return; }\n"
        "      for (const item of val) { if (traversalTruncated) return; traverse(item, depth + 1); }\n"
        "      return;\n"
        "    }\n"
        "    const record = val as Record<string, unknown>;\n"
        "    // Match collectOutputText: only extract text from {type: \"text\", text: ...}\n"
        "    // objects, not from metadata keys like \"type\".\n"
        "    if (record.type === 'text' && typeof record.text === 'string') {\n"
        "      update(record.text);\n"
        "      return;\n"
        "    }\n"
        "    let keyCount = 0;\n"
        "    for (const key of OUTPUT_TEXT_KEYS) {\n"
        "      if (!(key in record)) continue;\n"
        "      if (keyCount >= GUARD_OBJECT_KEY_LIMIT) { traversalTruncated = true; return; }\n"
        "      keyCount++;\n"
        "      if (traversalTruncated) return;\n"
        "      traverse(record[key], depth + 1);\n"
        "    }\n"
        "  }\n"
        "  try {\n"
        "    traverse(value, 0);\n"
        "  } catch {\n"
        "    traversalTruncated = true;\n"
        "  }\n"
        "  return {\n"
        "    sha256: traversalTruncated ? null : hash.digest('hex'),\n"
        "    chars,\n"
        "    textForExcerpt,\n"
        "    excerptTruncated,\n"
        "    traversalTruncated,\n"
        "  };\n"
        "}\n"
        "\n"
        "function sourcePathFromToolInput(toolInput: Record<string, unknown>): string | null {\n"
        "  for (const key of ['file_path', 'filePath', 'path', 'file', 'filename']) {\n"
        "    const value = toolInput[key];\n"
        "    if (typeof value === 'string' && value.trim()) return value.trim();\n"
        "  }\n"
        "  return null;\n"
        "}\n"
        "\n"
        "function sourceFileRefForPostToolUse(\n"
        "  event: Record<string, unknown>,\n"
        "  toolInput: Record<string, unknown>,\n"
        "  digest: OutputDigest,\n"
        "): { version: number; kind: string; path: string; tool_input_path: string; output_sha256: string; output_chars: number } | null {\n"
        "  const toolName = typeof event.toolName === 'string' ? event.toolName : '';\n"
        "  if (!GUARD_SOURCE_REF_ALLOWED_TOOL_NAMES.has(toolName)) return null;\n"
        "  if (!digest.sha256 || digest.traversalTruncated) return null;\n"
        "  if (digest.chars > GUARD_SOURCE_REF_MAX_OUTPUT_CHARS) return null;\n"
        "  const path = sourcePathFromToolInput(toolInput);\n"
        "  if (!path) return null;\n"
        "  return {\n"
        "    version: 1,\n"
        "    kind: 'source_file',\n"
        "    path,\n"
        "    tool_input_path: path,\n"
        "    output_sha256: digest.sha256,\n"
        "    output_chars: digest.chars,\n"
        "  };\n"
        "}\n"
        "\n"
        "type BoundedValue = { value: unknown; truncated: boolean };\n"
        'const OUTPUT_TEXT_KEYS = ["stdout", "stderr", "output", "content", "result", "message", "text"] as const;\n'
        "\n"
        "function truncateText(value: string, limit = GUARD_TEXT_LIMIT_CHARS): string {\n"
        "  if (value.length <= limit) return value;\n"
        "  return `${value.slice(0, Math.max(limit, 0))}\\n...[truncated by HOL Guard]...`;\n"
        "}\n"
        "\n"
        "function boundValue(value: unknown, depth = 0, seen = new WeakSet<object>()): BoundedValue {\n"
        "  if (typeof value === 'string') {\n"
        "    return value.length <= GUARD_TEXT_LIMIT_CHARS\n"
        "      ? { value, truncated: false }\n"
        "      : { value: truncateText(value), truncated: true };\n"
        "  }\n"
        "  if (value === undefined) return { value: undefined, truncated: false };\n"
        "  if (typeof value === 'bigint') return { value: value.toString(), truncated: false };\n"
        "  if (\n"
        "    value === null ||\n"
        "    typeof value === 'number' ||\n"
        "    typeof value === 'boolean'\n"
        "  ) {\n"
        "    return { value, truncated: false };\n"
        "  }\n"
        "  if (typeof value !== 'object') {\n"
        "    return { value: String(value), truncated: true };\n"
        "  }\n"
        "  const objectValue = value as object;\n"
        "  if (seen.has(objectValue)) {\n"
        "    return { value: '[cycle omitted by HOL Guard]', truncated: true };\n"
        "  }\n"
        "  if (depth > GUARD_MAX_DEPTH) {\n"
        "    return { value: '[deep object omitted by HOL Guard]', truncated: true };\n"
        "  }\n"
        "  seen.add(objectValue);\n"
        "  try {\n"
        "    if (Array.isArray(value)) {\n"
        "      const truncated = value.length > GUARD_CONTENT_ITEM_LIMIT;\n"
        "      const items = value.slice(0, GUARD_CONTENT_ITEM_LIMIT);\n"
        "      const nextItems: unknown[] = [];\n"
        "      let childTruncated = truncated;\n"
        "      for (const item of items) {\n"
        "        const next = boundValue(item, depth + 1, seen);\n"
        "        nextItems.push(next.value);\n"
        "        childTruncated = childTruncated || next.truncated;\n"
        "      }\n"
        "      return { value: nextItems, truncated: childTruncated };\n"
        "    }\n"
        "    const record = value as Record<string, unknown>;\n"
        "    const nextRecord: Record<string, unknown> = {};\n"
        "    let truncated = false;\n"
        "    let keyCount = 0;\n"
        "    for (const key in record) {\n"
        "      if (!Object.prototype.hasOwnProperty.call(record, key)) continue;\n"
        "      if (keyCount >= GUARD_OBJECT_KEY_LIMIT) {\n"
        "        truncated = true;\n"
        "        break;\n"
        "      }\n"
        "      keyCount += 1;\n"
        "      const entryValue = record[key];\n"
        "      const next = boundValue(entryValue, depth + 1, seen);\n"
        "      nextRecord[key] = next.value;\n"
        "      truncated = truncated || next.truncated;\n"
        "    }\n"
        "    return { value: nextRecord, truncated };\n"
        "  } finally {\n"
        "    seen.delete(objectValue);\n"
        "  }\n"
        "}\n"
        "\n"
        "function appendBoundedText(accumulator: { text: string; truncated: boolean }, value: string): void {\n"
        "  if (accumulator.truncated || value.length === 0) return;\n"
        '  const prefix = accumulator.text ? "\\n" : "";\n'
        "  const available = GUARD_TEXT_LIMIT_CHARS - accumulator.text.length - prefix.length;\n"
        "  if (available <= 0) {\n"
        "    accumulator.truncated = true;\n"
        "    return;\n"
        "  }\n"
        "  if (value.length > available) {\n"
        "    accumulator.text += `${prefix}${value.slice(0, available)}`;\n"
        "    accumulator.truncated = true;\n"
        "    return;\n"
        "  }\n"
        "  accumulator.text += `${prefix}${value}`;\n"
        "}\n"
        "\n"
        "function collectOutputText(\n"
        "  value: unknown,\n"
        "  accumulator: { text: string; truncated: boolean; itemCount: number },\n"
        "  depth = 0,\n"
        "  seen = new WeakSet<object>(),\n"
        "): void {\n"
        "  if (accumulator.truncated) return;\n"
        "  if (typeof value === 'string') {\n"
        "    appendBoundedText(accumulator, value);\n"
        "    return;\n"
        "  }\n"
        "  if (typeof value === 'bigint') {\n"
        "    appendBoundedText(accumulator, value.toString());\n"
        "    return;\n"
        "  }\n"
        "  if (\n"
        "    value === undefined ||\n"
        "    value === null ||\n"
        "    typeof value === 'number' ||\n"
        "    typeof value === 'boolean'\n"
        "  ) {\n"
        "    return;\n"
        "  }\n"
        "  if (typeof value !== 'object') {\n"
        "    accumulator.truncated = true;\n"
        "    return;\n"
        "  }\n"
        "  const objectValue = value as object;\n"
        "  if (seen.has(objectValue) || depth > GUARD_MAX_DEPTH) {\n"
        "    accumulator.truncated = true;\n"
        "    return;\n"
        "  }\n"
        "  seen.add(objectValue);\n"
        "  try {\n"
        "    if (Array.isArray(value)) {\n"
        "      const arrayItems = value as unknown[];\n"
        "      for (const item of arrayItems) {\n"
        "        if (accumulator.itemCount >= GUARD_CONTENT_ITEM_LIMIT) {\n"
        "          accumulator.truncated = true;\n"
        "          break;\n"
        "        }\n"
        "        accumulator.itemCount += 1;\n"
        "        collectOutputText(item, accumulator, depth + 1, seen);\n"
        "        if (accumulator.truncated) break;\n"
        "      }\n"
        "      if (arrayItems.length > GUARD_CONTENT_ITEM_LIMIT) accumulator.truncated = true;\n"
        "      return;\n"
        "    }\n"
        "    const record = value as Record<string, unknown>;\n"
        "    if (record.type === 'text' && typeof record.text === 'string') {\n"
        "      appendBoundedText(accumulator, record.text);\n"
        "      return;\n"
        "    }\n"
        "    for (const key of OUTPUT_TEXT_KEYS) {\n"
        "      if (!(key in record)) continue;\n"
        "      collectOutputText(record[key], accumulator, depth + 1, seen);\n"
        "      if (accumulator.truncated) break;\n"
        "    }\n"
        "  } finally {\n"
        "    seen.delete(objectValue);\n"
        "  }\n"
        "}\n"
        "\n"
        "function boundedOutputText(value: unknown): BoundedValue {\n"
        "  const accumulator = { text: '', truncated: false, itemCount: 0 };\n"
        "  collectOutputText(value, accumulator);\n"
        "  return { value: accumulator.text, truncated: accumulator.truncated };\n"
        "}\n"
        "\n"
        "function toolCallIdKey(value: unknown): string | null {\n"
        "  if (typeof value !== 'string') return null;\n"
        "  const trimmed = value.trim();\n"
        "  return trimmed.length > 0 ? trimmed : null;\n"
        "}\n"
        "\n"
        "function base64Url(value: Buffer): string {\n"
        "  return value.toString('base64url');\n"
        "}\n"
        "\n"
        "function encryptedPayload(serializedPayload: string) {\n"
        "  const key = randomBytes(32);\n"
        "  const nonce = randomBytes(12);\n"
        "  const cipher = createCipheriv('aes-256-gcm', key, nonce);\n"
        "  const ciphertext = Buffer.concat([\n"
        "    cipher.update(serializedPayload, 'utf8'),\n"
        "    cipher.final(),\n"
        "    cipher.getAuthTag(),\n"
        "  ]);\n"
        "  return { ciphertext, key: base64Url(key), nonce: base64Url(nonce) };\n"
        "}\n"
        "\n"
        "function referencedPayload(payload: Record<string, unknown>, serializedPayload: string) {\n"
        "  const directory = mkdtempSync(join(tmpdir(), 'hol-guard-hook-payload-'));\n"
        "  try { chmodSync(directory, 0o700); } catch {}\n"
        "  const path = join(directory, 'payload.json');\n"
        "  const encrypted = encryptedPayload(serializedPayload);\n"
        "  writeFileSync(path, encrypted.ciphertext, { mode: 0o600 });\n"
        "  const sha256 = createHash('sha256').update(encrypted.ciphertext).digest('hex');\n"
        "  const referencePayload: Record<string, unknown> = {\n"
        "    hook_event_name: payload.hook_event_name,\n"
        "    config_path: payload.config_path,\n"
        "    tool_name: payload.tool_name,\n"
        "    is_error: payload.is_error,\n"
        "    guard_payload_ref: {\n"
        "      version: 1,\n"
        "      path,\n"
        "      sha256,\n"
        "      encoding: 'json',\n"
        "      encryption: 'aes-256-gcm',\n"
        "      key: encrypted.key,\n"
        "      nonce: encrypted.nonce,\n"
        "      serialized_chars: serializedPayload.length,\n"
        "    },\n"
        "  };\n"
        "  return {\n"
        "    payload: referencePayload,\n"
        "    cleanup: () => { try { rmSync(directory, { recursive: true, force: true }); } catch {} },\n"
        "  };\n"
        "}\n"
        "\n"
        "async function daemonGuardResponse(\n"
        "  serializedPayload: string,\n"
        "  cwd?: string,\n"
        "): Promise<GuardResponse | null> {\n"
        "  if (typeof fetch !== 'function') return null;\n"
        "  let port = 0;\n"
        "  let authToken = '';\n"
        "  try {\n"
        "    const daemonState = JSON.parse(\n"
        "      readFileSync(join(GUARD_HOME, 'daemon-state.json'), 'utf8'),\n"
        "    ) as { port?: unknown };\n"
        "    port = typeof daemonState.port === 'number' ? daemonState.port : 0;\n"
        "    authToken = readFileSync(join(GUARD_HOME, 'daemon-auth-token'), 'utf8').trim();\n"
        "  } catch {\n"
        "    return null;\n"
        "  }\n"
        "  if (!(port > 0) || authToken.length === 0) return null;\n"
        '  const workspace = typeof cwd === "string" && cwd ? cwd : process.cwd();\n'
        "  const params = new URLSearchParams({ 'guard-home': GUARD_HOME });\n"
        "  if (workspace) params.set('workspace', workspace);\n"
        "  if (!GUARD_HOME_DIR_IS_DEFAULT && GUARD_HOME_DIR) params.set('home', GUARD_HOME_DIR);\n"
        "  const controller = typeof AbortController === 'function' ? new AbortController() : undefined;\n"
        "  const timeoutHandle = setTimeout(() => controller?.abort(), Math.max(GUARD_TIMEOUT_MS - 500, 1));\n"
        "  try {\n"
        "    const response = await fetch(`http://127.0.0.1:${port}/v1/hooks/pi?${params.toString()}`, {\n"
        "      method: 'POST',\n"
        "      headers: {\n"
        "        'Content-Type': 'application/json',\n"
        "        'X-Guard-Token': authToken,\n"
        "      },\n"
        "      body: serializedPayload,\n"
        "      signal: controller?.signal,\n"
        "    });\n"
        "    if (!response.ok) return null;\n"
        "    const raw = (await response.text()).trim();\n"
        "    if (!raw) return {};\n"
        "    const parsed = JSON.parse(raw) as GuardResponse;\n"
        "    return parsed && typeof parsed === 'object' ? parsed : null;\n"
        "  } catch {\n"
        "    return null;\n"
        "  } finally {\n"
        "    clearTimeout(timeoutHandle);\n"
        "  }\n"
        "}\n"
        "\n"
        "async function runGuard(\n"
        "  payload: Record<string, unknown>,\n"
        "  cwd?: string,\n"
        "  options?: { enforceSizeCap?: boolean },\n"
        "): Promise<GuardResponse> {\n"
        "  const args = [...GUARD_ARGS];\n"
        '  const workspace = typeof cwd === "string" && cwd ? cwd : process.cwd();\n'
        '  if (workspace) args.push("--workspace", workspace);\n'
        "  let payloadToSend = payload;\n"
        "  let serializedPayload = '';\n"
        "  let cleanupPayloadReference = () => {};\n"
        "  try {\n"
        "    serializedPayload = JSON.stringify(payloadToSend);\n"
        "  } catch (error) {\n"
        "    return {\n"
        '      decision: "deny",\n'
        "      reason: `HOL Guard could not serialize Pi hook payload: ${\n"
        "        error instanceof Error ? error.message : String(error)\n"
        "      }`,\n"
        "    };\n"
        "  }\n"
        "  if (\n"
        "    options?.enforceSizeCap === true &&\n"
        "    serializedPayload.length > GUARD_MAX_SERIALIZED_PAYLOAD_CHARS\n"
        "  ) {\n"
        "    const referenced = referencedPayload(payloadToSend, serializedPayload);\n"
        "    payloadToSend = referenced.payload;\n"
        "    cleanupPayloadReference = referenced.cleanup;\n"
        "    try {\n"
        "      serializedPayload = JSON.stringify(payloadToSend);\n"
        "    } catch (error) {\n"
        "      cleanupPayloadReference();\n"
        "      return {\n"
        '        decision: "deny",\n'
        "        reason: `HOL Guard could not serialize Pi hook payload reference: ${\n"
        "          error instanceof Error ? error.message : String(error)\n"
        "        }`,\n"
        "      };\n"
        "    }\n"
        "  }\n"
        "  if (\n"
        "    options?.enforceSizeCap === true &&\n"
        "    serializedPayload.length > GUARD_MAX_SERIALIZED_PAYLOAD_CHARS\n"
        "  ) {\n"
        "    cleanupPayloadReference();\n"
        "    return {\n"
        '      decision: "deny",\n'
        '      reason: "HOL Guard blocked this Pi hook payload before review because it exceeded "\n'
        '        + "the safe size limit.",\n'
        "    };\n"
        "  }\n"
        "  const daemonResponse = await daemonGuardResponse(serializedPayload, cwd);\n"
        "  if (daemonResponse) {\n"
        "    cleanupPayloadReference();\n"
        "    return daemonResponse;\n"
        "  }\n"
        "  let result: ReturnType<typeof spawnSync<string>> | null = null;\n"
        "  for (const command of GUARD_COMMAND_CANDIDATES) {\n"
        "    result = spawnSync(command, args, {\n"
        "      input: `${serializedPayload}\\n`,\n"
        '      encoding: "utf-8",\n'
        "      timeout: GUARD_TIMEOUT_MS,\n"
        "    });\n"
        "    const resultError = result.error as (Error & { code?: unknown }) | undefined;\n"
        "    if (!(result.error && resultError?.code === 'ENOENT')) break;\n"
        "  }\n"
        "  cleanupPayloadReference();\n"
        "  if (result === null) {\n"
        "    return {\n"
        '      decision: "deny",\n'
        '      reason: "HOL Guard Pi hook failed before completing review: Guard CLI was not found.",\n'
        "    };\n"
        "  }\n"
        "  if (result.error) {\n"
        "    const resultError = result.error as (Error & { code?: unknown }) | undefined;\n"
        "    const errorMessage = resultError instanceof Error ? resultError.message : String(result.error);\n"
        "    const errorCode = typeof resultError?.code === 'string' ? resultError.code : '';\n"
        "    return {\n"
        '      decision: "deny",\n'
        "      reason: errorCode === 'ETIMEDOUT' || result.error?.name === 'TimeoutError'\n"
        "        ? `HOL Guard Pi hook timed out after ${GUARD_TIMEOUT_MS}ms while reviewing this action.`\n"
        "        : `HOL Guard Pi hook failed before completing review: ${errorMessage}`,\n"
        "    };\n"
        "  }\n"
        '  const lines = (result.stdout ?? "").split(/\\r?\\n/).map((line) => line.trim()).filter(Boolean);\n'
        "  const lastLine = lines.length > 0 ? lines[lines.length - 1] : null;\n"
        "  if (lastLine) {\n"
        "    try {\n"
        "      const parsed = JSON.parse(lastLine) as GuardResponse;\n"
        '      if (parsed && typeof parsed === "object") return parsed;\n'
        "    } catch {}\n"
        "  }\n"
        "  if ((result.status ?? 0) !== 0) {\n"
        "    return {\n"
        '      decision: "deny",\n'
        '      reason: (result.stderr ?? "").trim() || "Blocked by HOL Guard.",\n'
        "    };\n"
        "  }\n"
        '  return { decision: "allow" };\n'
        "}\n"
        "\n"
        "function blockedToolResult(reason: string, details: unknown) {\n"
        "  return {\n"
        '    content: [{ type: "text", text: reason }],\n'
        "    details,\n"
        "    isError: true,\n"
        "  };\n"
        "}\n"
        "\n"
        "function reviewedToolResult(content: unknown, details: unknown, isError?: boolean) {\n"
        "  let body = '';\n"
        "  if (Array.isArray(content)) {\n"
        "    body = boundedOutputText(content).value as string;\n"
        "  } else if (typeof content === 'string') {\n"
        "    body = content;\n"
        "  } else if (content !== undefined && content !== null) {\n"
        "    try { body = JSON.stringify(content); } catch {}\n"
        "  }\n"
        "  const result = {\n"
        '    content: body.length > 0 ? [{ type: "text", text: body }] : [],\n'
        "    details,\n"
        "  } as { content: unknown[]; details: unknown; isError?: boolean };\n"
        "  if (isError) result.isError = true;\n"
        "  return result;\n"
        "}\n"
        "\n"
        "export default function (pi: ExtensionAPI) {\n"
        "  const blockedToolResults = new Map<string, string>();\n"
        '  pi.on("input", async (event, ctx) => {\n'
        '    if (event.source === "extension") return { action: "continue" };\n'
        "    const response = await runGuard(\n"
        '      { hook_event_name: "UserPromptSubmit", prompt: event.text, config_path: GUARD_CONFIG_PATH },\n'
        "      ctx.cwd,\n"
        "    );\n"
        '    if (response.decision === "deny") {\n'
        '      ctx.ui.notify(response.reason ?? "Blocked by HOL Guard.", "warning");\n'
        '      return { action: "handled", handled: true };\n'
        "    }\n"
        '    return { action: "continue" };\n'
        "  });\n"
        '  pi.on("tool_call", async (event, ctx) => {\n'
        "    const toolInput =\n"
        "      (event as { input?: Record<string, unknown> }).input ??\n"
        "      (event as { toolInput?: Record<string, unknown> }).toolInput ??\n"
        "      (event as { arguments?: Record<string, unknown> }).arguments ??\n"
        "      {};\n"
        "    const response = await runGuard(\n"
        "      {\n"
        '        hook_event_name: "PreToolUse",\n'
        "        config_path: GUARD_CONFIG_PATH,\n"
        "        tool_name: event.toolName,\n"
        "        tool_input: toolInput,\n"
        "      },\n"
        "      ctx.cwd,\n"
        "    );\n"
        '    if (response.decision === "deny") {\n'
        '      ctx.ui.notify(response.reason ?? "Blocked by HOL Guard.", "warning");\n'
        '      return { block: true, reason: response.reason ?? "Blocked by HOL Guard." };\n'
        "    }\n"
        "    return undefined;\n"
        "  });\n"
        '  pi.on("message_end", async (event) => {\n'
        '    if (event.message.role !== "toolResult") return;\n'
        "    const toolCallId = toolCallIdKey(event.message.toolCallId);\n"
        "    if (!toolCallId) return;\n"
        "    const reason = blockedToolResults.get(toolCallId);\n"
        "    if (!reason) return;\n"
        "    blockedToolResults.delete(toolCallId);\n"
        "    return {\n"
        "      message: {\n"
        "        ...event.message,\n"
        '        content: [{ type: "text", text: reason }],\n'
        "        isError: true,\n"
        "      },\n"
        "    };\n"
        "  });\n"
        '  pi.on("tool_result", async (event, ctx) => {\n'
        "    const toolInput =\n"
        "      (event as { input?: Record<string, unknown> }).input ??\n"
        "      (event as { toolInput?: Record<string, unknown> }).toolInput ??\n"
        "      (event as { arguments?: Record<string, unknown> }).arguments ??\n"
        "      {};\n"
        "    const digest = digestOutputText(event.content);\n"
        "    const boundedContent = boundValue(event.content);\n"
        "    const boundedStdout = boundedOutputText(event.content);\n"
        "    const outputTruncated = boundedContent.truncated || boundedStdout.truncated || digest.excerptTruncated || digest.traversalTruncated;\n"
        "    const toolOutput = digest.textForExcerpt || (boundedStdout.value as string);\n"
        "    const reviewedContent = outputTruncated ? [{ type: 'text', text: toolOutput }] : boundedContent.value;\n"
        "    const sourceRef = sourceFileRefForPostToolUse(event as Record<string, unknown>, toolInput, digest);\n"
        "    const guardPayload: Record<string, unknown> = {\n"
        '        hook_event_name: "PostToolUse",\n'
        "        config_path: GUARD_CONFIG_PATH,\n"
        "        tool_name: event.toolName,\n"
        "        tool_input: toolInput,\n"
        "        stdout: toolOutput,\n"
        "        is_error: event.isError === true,\n"
        "    };\n"
        "    if (sourceRef) {\n"
        "      guardPayload.guard_source_ref = sourceRef;\n"
        "      guardPayload.tool_response_summary = {\n"
        "        kind: 'text',\n"
        "        excerpt_chars: toolOutput.length,\n"
        "        output_chars: digest.chars,\n"
        "        output_sha256: digest.sha256,\n"
        "        excerpt_truncated: outputTruncated,\n"
        "      };\n"
        "    } else {\n"
        "      guardPayload.tool_response = event.content;\n"
        "    }\n"
        "    const response = await runGuard(\n"
        "      guardPayload,\n"
        "      ctx.cwd,\n"
        "      { enforceSizeCap: true },\n"
        "    );\n"
        '    if (response.decision === "deny") {\n'
        '      const reason = response.reason ?? "Blocked by HOL Guard.";\n'
        "      const toolCallId = toolCallIdKey(event.toolCallId);\n"
        "      if (toolCallId) blockedToolResults.set(toolCallId, reason);\n"
        '      ctx.ui.notify(reason, "warning");\n'
        "      return blockedToolResult(reason, event.details);\n"
        "    }\n"
        "    if (outputTruncated) {\n"
        '      if (response.model_output_action === "allow_original" &&\n'
        "          typeof response.reviewed_output_sha256 === 'string' &&\n"
        "          response.reviewed_output_sha256 === digest.sha256) {\n"
        "        return undefined;\n"
        "      }\n"
        "      const notice = response.reason ||\n"
        '        "HOL Guard returned a reviewed excerpt because this output could not be fully proven safe within local limits.";\n'
        '      if (response.notice === "excerpt" || response.model_output_action === "replace_with_reviewed_excerpt") {\n'
        '        ctx.ui.notify(notice, "info");\n'
        "      }\n"
        "      return reviewedToolResult(reviewedContent, event.details, event.isError === true);\n"
        "    }\n"
        "    return undefined;\n"
        "}\n"
    )
