"""Build derived package resources without editing authored inputs or expectations.

Hatch calls this for source installs. CI may reuse outputs produced by its own
native build. The untracked manifest binds all inputs and every staged file.
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from collections.abc import Iterator
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = Path("src/codex_plugin_scanner/guard/contracts/data")
STATE = Path("build/guard-resources/manifest.json")
SCHEMA = "guard.build-owned-resources.v1"
MAX_FILE_BYTES = 8 * 1024 * 1024


def _regular(root: Path, path: Path) -> bytes:
    """Read bounded regular files without traversing repository-relative links."""
    relative = path.relative_to(root)
    current = root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            raise ValueError(f"resource path traverses a symlink: {relative}")
    if not path.is_file() or path.stat().st_size > MAX_FILE_BYTES:
        raise ValueError(f"invalid resource input: {relative}")
    return path.read_bytes()


def input_paths(root: Path) -> list[Path]:
    """Enumerate authored inputs, generator code and locked native dependencies."""
    paths = {
        root / "rust/Cargo.toml",
        root / "rust/Cargo.lock",
        root / "pyproject.toml",
        root / "hatch_build.py",
        root / "scripts/build_guard_resources.py",
        root / "scripts/build_native_command_program.py",
        root / "contracts/extensions/trust-class-map.v1.json",
    }
    for directory, pattern in (
        ("contributions/command-sources", "*.json"),
        ("contributions/mcp-servers", "*.json"),
        ("contracts/extensions", "*.schema.json"),
        ("contracts/mcp-servers", "*.schema.json"),
        ("rust/build_support", "*.rs"),
    ):
        parent = root / directory
        if parent.is_symlink():
            raise ValueError("authored input directory must not be a symlink")
        paths.update(parent.glob(pattern))
    for crate in (root / "rust/crates").iterdir():
        if crate.is_symlink():
            raise ValueError("native crate must not be a symlink")
        for name in ("Cargo.toml", "build.rs"):
            if (crate / name).is_file():
                paths.add(crate / name)
        if (crate / "src").is_dir():
            paths.update(p for p in (crate / "src").rglob("*") if p.suffix in (".rs", ".json"))
    return sorted(paths, key=lambda path: path.relative_to(root).as_posix())


def input_digest(root: Path) -> str:
    """Bind names and bytes without timestamps, absolute paths or Git history."""
    digest = hashlib.sha256(b"hol-guard.build-owned-inputs.v1\0")
    for path in input_paths(root):
        name = path.relative_to(root).as_posix().encode()
        content = _regular(root, path).replace(b"\r\n", b"\n")
        digest.update(len(name).to_bytes(8, "big"))
        digest.update(name)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return digest.hexdigest()


def expected_outputs(root: Path) -> set[str]:
    """Require completeness independently of the manifest supplied by a producer."""
    names = {"native-command-program.v1.json", "command-catalog.v1.json"}
    result = {"contracts/extensions/" + name for name in names}
    result.update((PACKAGE / "extensions" / name).as_posix() for name in names)
    for source in (root / "contributions/command-sources").glob("command.*.json"):
        result.add("contributions/extensions/" + source.name)
        result.add((PACKAGE / "extensions/contributions" / source.name).as_posix())
    for group, target in (("extensions", "extensions"), ("mcp-servers", "mcp_servers")):
        result.update(
            (PACKAGE / target / p.name).as_posix() for p in (root / "contracts" / group).glob("*.schema.json")
        )
    result.add((PACKAGE / "extensions/trust-class-map.v1.json").as_posix())
    result.update(
        (PACKAGE / "mcp_servers/contributions" / p.name).as_posix()
        for p in (root / "contributions/mcp-servers").glob("*.json")
    )
    return result


def _atomic_write(root: Path, path: Path, content: bytes) -> None:
    """Replace complete generated bytes, never write through a link."""
    if len(content) > MAX_FILE_BYTES:
        raise ValueError("generated resource exceeds its bound")
    current = root
    for part in path.relative_to(root).parts:
        current /= part
        if current.is_symlink():
            raise ValueError("generated resource traverses a symlink")
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, name = tempfile.mkstemp(prefix=".guard-build-", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(content)
        os.chmod(name, 0o644)
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


@contextlib.contextmanager
def _lock(root: Path) -> Iterator[None]:
    """Serialize source builds with an OS lock released on process exit."""
    path = root / "build/guard-resources/build.lock"
    if path.is_symlink() or path.parent.is_symlink() or (root / "build").is_symlink():
        raise ValueError("build lock traverses a symlink")
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a+b") as handle:
        if handle.seek(0, 2) == 0:
            handle.write(b"0")
            handle.flush()
        handle.seek(0)
        if os.name == "nt":
            import msvcrt

            def acquire() -> None:
                msvcrt.locking(handle.fileno(), msvcrt.LK_NBLCK, 1)

            def release() -> None:
                handle.seek(0)
                msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
        else:
            import fcntl

            def acquire() -> None:
                fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)

            def release() -> None:
                fcntl.flock(handle, fcntl.LOCK_UN)

        deadline = time.monotonic() + 900
        while True:
            try:
                acquire()
                break
            except OSError:
                if time.monotonic() >= deadline:
                    raise TimeoutError("source build lock timed out") from None
                time.sleep(0.1)
        try:
            yield
        finally:
            release()


def _unique(pairs: list[tuple[str, object]]) -> dict:
    """Reject ambiguous manifest keys."""
    value = {}
    for key, item in pairs:
        if key in value:
            raise ValueError("duplicate manifest key")
        value[key] = item
    return value


def current_manifest(root: Path) -> dict | None:
    """Accept only a complete same-input output set with matching file hashes."""
    try:
        manifest = json.loads(_regular(root, root / STATE), object_pairs_hook=_unique)
        outputs = manifest["outputs"]
        if manifest["schema"] != SCHEMA or manifest["input_digest"] != input_digest(root):
            return None
        if set(outputs) != expected_outputs(root):
            return None
        # A stale removed extension must not survive outside the manifest.
        package_files = {
            path.relative_to(root).as_posix()
            for directory in (root / PACKAGE / "extensions", root / PACKAGE / "mcp_servers")
            for path in directory.rglob("*.json")
        }
        if package_files != {name for name in outputs if name.startswith(PACKAGE.as_posix() + "/")}:
            return None
        for name, digest in outputs.items():
            if hashlib.sha256(_regular(root, root / name)).hexdigest() != digest:
                return None
        return manifest
    except (OSError, ValueError, KeyError, TypeError):
        return None


def _build_compiler(root: Path) -> Path:
    """Cargo generates the program before compiling the source-compiler binary."""
    cargo = shutil.which("cargo")
    if cargo is None:
        raise RuntimeError("A source build requires Rust 1.88+; install Rust or use a prebuilt HOL Guard wheel.")
    command = [
        cargo,
        "build",
        "--locked",
        "--manifest-path",
        str(root / "rust/Cargo.toml"),
        "-p",
        "guard-command",
        "--bin",
        "guard-command-source",
        "--message-format=json",
    ]
    completed = subprocess.run(command, cwd=root / "rust", stdout=subprocess.PIPE, text=True, timeout=900, check=False)
    if completed.returncode:
        raise RuntimeError("native source compiler build failed")
    for line in completed.stdout.splitlines():
        item = json.loads(line)
        if (
            item.get("reason") == "compiler-artifact"
            and item.get("target", {}).get("name") == "guard-command-source"
            and item.get("executable")
        ):
            return Path(item["executable"])
    raise RuntimeError("Cargo did not produce a source compiler")


def _stage(root: Path, compiler: Path) -> list[Path]:
    """Stage compiler output and authored copies; never rewrite test expectations."""
    command = [sys.executable, str(root / "scripts/build_native_command_program.py"), "--compiler", str(compiler)]
    subprocess.run(command, cwd=root, check=True, timeout=180)
    subprocess.run([*command, "--check"], cwd=root, check=True, timeout=180)
    paths = [
        root / "contracts/extensions" / name for name in ("native-command-program.v1.json", "command-catalog.v1.json")
    ]
    descriptors = sorted((root / "contributions/extensions").glob("command.*.json"))
    paths.extend(descriptors)
    copies = [(path, root / PACKAGE / "extensions" / path.name) for path in paths[:2]]
    copies += [(path, root / PACKAGE / "extensions/contributions" / path.name) for path in descriptors]
    for group, target in (("extensions", "extensions"), ("mcp-servers", "mcp_servers")):
        for path in sorted((root / "contracts" / group).glob("*.schema.json")):
            copies.append((path, root / PACKAGE / target / path.name))
    copies.append(
        (root / "contracts/extensions/trust-class-map.v1.json", root / PACKAGE / "extensions/trust-class-map.v1.json")
    )
    for path in sorted((root / "contributions/mcp-servers").glob("*.json")):
        copies.append((path, root / PACKAGE / "mcp_servers/contributions" / path.name))
    for source, destination in copies:
        _atomic_write(root, destination, _regular(root, source))
        paths.append(destination)
    expected = set(paths)
    for directory in (root / PACKAGE / "extensions", root / PACKAGE / "mcp_servers"):
        for path in directory.rglob("*.json"):
            if path not in expected:
                _regular(root, path)
                path.unlink()
    if {p.relative_to(root).as_posix() for p in paths} != expected_outputs(root):
        raise RuntimeError("compiler output did not cover every authored source")
    return sorted(set(paths))


def prepare(root: Path = ROOT, *, compiler: Path | None = None, force: bool = False) -> dict:
    """Build source-install resources or reuse validated same-run staged output."""
    with _lock(root):
        manifest = current_manifest(root)
        if manifest is not None and compiler is None and not force:
            return manifest
        before = input_digest(root)
        chosen = compiler.resolve(strict=True) if compiler else _build_compiler(root)
        outputs = _stage(root, chosen)
        if input_digest(root) != before:
            raise RuntimeError("authored inputs changed during resource preparation")
        manifest = {
            "schema": SCHEMA,
            "input_digest": before,
            "outputs": {
                path.relative_to(root).as_posix(): hashlib.sha256(_regular(root, path)).hexdigest() for path in outputs
            },
        }
        _atomic_write(root, root / STATE, (json.dumps(manifest, sort_keys=True, indent=2) + "\n").encode())
        return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        if current_manifest(ROOT) is None:
            parser.error("build-owned resources are missing, modified, or belong to different inputs")
    else:
        prepare(compiler=args.compiler)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
