"""Shared constants for browserless remote agent pairing."""

REMOTE_PAIRING_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
REMOTE_PAIRING_CODE_PREFIX = "HLG"
REMOTE_PAIRING_CODE_MIN_LENGTH = 6
REMOTE_PAIRING_CODE_MAX_LENGTH = 32
